items<public> := module:
    item_tables<public> := module:
        using { item_ids }
        
        ItemTables<public>: [][][]int = array:
            # Chapter 1, Season 0
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleCommon
                    PumpShotgunCommon
                    SubmachineGunCommon
                    SemiAutoPistolCommon
                    RevolverCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SubmachineGunUncommon
                    TacticalSubmachineGunUncommon
                    SemiAutoPistolUncommon
                    RevolverUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleUncommon
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    SubmachineGunRare
                    TacticalSubmachineGunRare
                    SemiAutoPistolRare
                    RevolverRare
                    BoltActionSniperRifleRare
                    GrenadeLauncherRare
                    RocketLauncherRare 
                array:
                    AssaultRifleBEpic
                    ScopedAssaultRifleEpic
                    TacticalShotgunEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    SemiAutoSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                array:
                    AssaultRifleBLegendary
                    SemiAutoSniperRifleLegendary
                    BoltActionSniperRifleLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
            # Chapter 1, Season 1
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleCommon
                    PumpShotgunCommon
                    SubmachineGunCommon
                    SemiAutoPistolCommon
                    RevolverCommon
                    SuppressedSubmachineGunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SubmachineGunUncommon
                    TacticalSubmachineGunUncommon
                    SemiAutoPistolUncommon
                    RevolverUncommon
                    SuppressedSubmachineGunUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleUncommon
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    SubmachineGunRare
                    TacticalSubmachineGunRare
                    SemiAutoPistolRare
                    RevolverRare
                    BoltActionSniperRifleRare
                    GrenadeLauncherRare
                    RocketLauncherRare
                    SuppressedSubmachineGunRare
                    PumpkinLauncherRare
                array:
                    AssaultRifleBEpic
                    ScopedAssaultRifleEpic
                    TacticalShotgunEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    SemiAutoSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    PumpkinLauncherEpic
                array:
                    AssaultRifleBLegendary
                    SemiAutoSniperRifleLegendary
                    BoltActionSniperRifleLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    PumpkinLauncherLegendary
            # Chapter 1, Season 2
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleCommon
                    PumpShotgunCommon
                    SubmachineGunCommon
                    SemiAutoPistolCommon
                    RevolverCommon
                    SuppressedSubmachineGunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SubmachineGunUncommon
                    TacticalSubmachineGunUncommon
                    SemiAutoPistolUncommon
                    RevolverUncommon
                    SuppressedSubmachineGunUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleUncommon
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    SubmachineGunRare
                    TacticalSubmachineGunRare
                    SemiAutoPistolRare
                    RevolverRare
                    BoltActionSniperRifleRare
                    GrenadeLauncherRare
                    RocketLauncherRare
                    SuppressedSubmachineGunRare
                    SnowballLauncherRare
                array:
                    AssaultRifleBEpic
                    ScopedAssaultRifleEpic
                    TacticalShotgunEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    SemiAutoSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    CupidsCrossbowEpic
                    SnowballLauncherEpic
                array:
                    AssaultRifleBLegendary
                    SemiAutoSniperRifleLegendary
                    BoltActionSniperRifleLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    SemiAutoSuppressedPistolLegendary
                    SnowballLauncherLegendary
            # Chapter 1, Season 3
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleCommon
                    PumpShotgunCommon
                    SemiAutoPistolCommon
                    RevolverCommon
                    SuppressedSubmachineGunCommon
                    TacticalShotgunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    TacticalSubmachineGunUncommon
                    SemiAutoPistolUncommon
                    RevolverUncommon
                    SuppressedSubmachineGunUncommon
                    HuntingRifleUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleUncommon
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    TacticalSubmachineGunRare
                    SemiAutoPistolRare
                    RevolverRare
                    BoltActionSniperRifleRare
                    GrenadeLauncherRare
                    RocketLauncherRare
                    SuppressedSubmachineGunRare
                    EggLauncherRare
                    LightMachineGunRare
                    PumpShotgunRare
                    HuntingRifleRare
                    CrossbowRare
                array:
                    AssaultRifleBEpic
                    ScopedAssaultRifleEpic
                    TacticalShotgunEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    SemiAutoSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    EggLauncherEpic
                    LightMachineGunEpic
                    HeavyShotgunEpic
                    HandCannonEpic
                    CrossbowEpic
                array:
                    AssaultRifleBLegendary
                    SemiAutoSniperRifleLegendary
                    BoltActionSniperRifleLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    SemiAutoSuppressedPistolLegendary
                    EggLauncherLegendary
                    HeavyShotgunLegendary
                    HandCannonLegendary
            # Chapter 1, Season 4
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleCommon
                    SemiAutoPistolCommon
                    RevolverCommon
                    SuppressedSubmachineGunCommon
                    TacticalShotgunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    TacticalSubmachineGunUncommon
                    SemiAutoPistolUncommon
                    RevolverUncommon
                    SuppressedSubmachineGunUncommon
                    HuntingRifleUncommon
                    DrumGunUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleUncommon
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    TacticalSubmachineGunRare
                    SemiAutoPistolRare
                    RevolverRare
                    BoltActionSniperRifleRare
                    GrenadeLauncherRare
                    RocketLauncherRare
                    SuppressedSubmachineGunRare
                    EggLauncherRare
                    LightMachineGunRare
                    PumpShotgunRare
                    HuntingRifleRare
                    DrumGunRare
                array:
                    AssaultRifleBEpic
                    ScopedAssaultRifleEpic
                    TacticalShotgunEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    SemiAutoSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    EggLauncherEpic
                    LightMachineGunEpic
                    HeavyShotgunEpic
                    HandCannonEpic
                    ThermalScopedAssaultRifleEpic
                    BurstAssaultRifleBEpic
                    DualPistolsEpic
                array:
                    AssaultRifleBLegendary
                    SemiAutoSniperRifleLegendary
                    BoltActionSniperRifleLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    SemiAutoSuppressedPistolLegendary
                    EggLauncherLegendary
                    HeavyShotgunLegendary
                    HandCannonLegendary
                    ThermalScopedAssaultRifleLegendary
                    BurstAssaultRifleBLegendary
                    DualPistolsLegendary
            # Chapter 1, Season 5
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleCommon
                    SemiAutoPistolCommon
                    SubmachineGunBCommon
                    TacticalShotgunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SemiAutoPistolUncommon
                    SuppressedSubmachineGunUncommon
                    HuntingRifleUncommon
                    SubmachineGunBUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleUncommon
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    BoltActionSniperRifleRare
                    GrenadeLauncherRare
                    SuppressedSubmachineGunRare
                    LightMachineGunRare
                    PumpShotgunRare
                    HuntingRifleRare
                    SubmachineGunBRare
                    SemiAutoSuppressedPistolRare
                    DualPistolsRare
                array:
                    AssaultRifleBEpic
                    ScopedAssaultRifleEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    SemiAutoSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    LightMachineGunEpic
                    HeavyShotgunEpic
                    HandCannonEpic
                    ThermalScopedAssaultRifleEpic
                    BurstAssaultRifleBEpic
                    DualPistolsEpic
                    SuppressedAssaultRifleEpic
                    DoubleBarrelEpic
                    SubmachineGunCEpic
                    HeavySniperRifleEpic
                array:
                    AssaultRifleBLegendary
                    SemiAutoSniperRifleLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    HeavyShotgunLegendary
                    HandCannonLegendary
                    ThermalScopedAssaultRifleLegendary
                    BurstAssaultRifleBLegendary
                    SuppressedAssaultRifleLegendary
                    DoubleBarrelLegendary
                    SubmachineGunCLegendary
                    HeavySniperRifleLegendary
            # Chapter 1, Season 6
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleCommon
                    SemiAutoPistolCommon
                    SubmachineGunBCommon
                    TacticalShotgunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SemiAutoPistolUncommon
                    HuntingRifleUncommon
                    SubmachineGunBUncommon
                    SixShooterUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleUncommon
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    BoltActionSniperRifleRare
                    GrenadeLauncherRare
                    PumpShotgunRare
                    HuntingRifleRare
                    SubmachineGunBRare
                    SemiAutoSuppressedPistolRare
                    HeavyAssaultRifleRare
                    SixShooterRare
                array:
                    AssaultRifleBEpic
                    ScopedAssaultRifleEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    HeavyShotgunEpic
                    HandCannonEpic
                    ThermalScopedAssaultRifleEpic
                    BurstAssaultRifleBEpic
                    SuppressedAssaultRifleEpic
                    DoubleBarrelEpic
                    SubmachineGunCEpic
                    HeavySniperRifleEpic
                    HeavyAssaultRifleEpic
                    PumpShotgunEpic
                    SixShooterEpic
                    QuadLauncherEpic
                array:
                    AssaultRifleBLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    HeavyShotgunLegendary
                    HandCannonLegendary
                    ThermalScopedAssaultRifleLegendary
                    BurstAssaultRifleBLegendary
                    SuppressedAssaultRifleLegendary
                    DoubleBarrelLegendary
                    SubmachineGunCLegendary
                    HeavySniperRifleLegendary
                    HeavyAssaultRifleLegendary
                    PumpShotgunLegendary
                    QuadLauncherLegendary
            # Chapter 1, Season 7
            array:
                array:
                    AssaultRifleCommon
                    SemiAutoPistolCommon
                    SuppressedSubmachineGunCommon
                    TacticalShotgunCommon
                    InfantryRifleCommon
                array:
                    AssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SemiAutoPistolUncommon
                    HuntingRifleUncommon
                    SuppressedSubmachineGunUncommon
                    ScopedAssaultRifleUncommon
                    InfantryRifleUncommon
                array:
                    AssaultRifleRare
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    GrenadeLauncherRare
                    PumpShotgunRare
                    HuntingRifleRare
                    SuppressedSubmachineGunRare
                    SemiAutoSuppressedPistolRare
                    HeavyAssaultRifleRare
                    InfantryRifleRare
                    DualPistolsRare
                array:
                    AssaultRifleBEpic
                    TacticalSubmachineGunEpic
                    SuppressedSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    HandCannonEpic
                    ThermalScopedAssaultRifleEpic
                    SuppressedAssaultRifleEpic
                    SubmachineGunCEpic
                    HeavySniperRifleEpic
                    HeavyAssaultRifleEpic
                    PumpShotgunEpic
                    DualPistolsEpic
                    ScopedRevolverEpic
                array:
                    AssaultRifleBLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    HandCannonLegendary
                    ThermalScopedAssaultRifleLegendary
                    SuppressedAssaultRifleLegendary
                    SubmachineGunCLegendary
                    HeavySniperRifleLegendary
                    HeavyAssaultRifleLegendary
                    PumpShotgunLegendary
                    ScopedRevolverLegendary
                    SuppressedSniperRifleLegendary
                array:
                    InfinityBlade
            # Chapter 1, Season 8
            array:
                array:
                    AssaultRifleCommon
                    SemiAutoPistolCommon
                    SuppressedSubmachineGunCommon
                    TacticalShotgunCommon
                    FlintKnockPistolCommon
                    HeavyAssaultRifleCommon
                array:
                    AssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SemiAutoPistolUncommon
                    HuntingRifleUncommon
                    SuppressedSubmachineGunUncommon
                    ScopedAssaultRifleUncommon
                    InfantryRifleUncommon
                    DrumGunUncommon
                    FlintKnockPistolUncommon
                array:
                    AssaultRifleRare
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    GrenadeLauncherRare
                    PumpShotgunRare
                    HuntingRifleRare
                    SuppressedSubmachineGunRare
                    SemiAutoSuppressedPistolRare
                    HeavyAssaultRifleRare
                    InfantryRifleRare
                    DualPistolsRare
                    DrumGunRare
                    HeavyAssaultRifleUncommon
                array:
                    AssaultRifleBEpic
                    TacticalSubmachineGunEpic
                    SuppressedSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    HandCannonEpic
                    ThermalScopedAssaultRifleEpic
                    SuppressedAssaultRifleEpic
                    SubmachineGunCEpic
                    HeavySniperRifleEpic
                    PumpShotgunEpic
                    DualPistolsEpic
                    ScopedRevolverEpic
                    InfantryRifleEpic
                array:
                    AssaultRifleBLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    HandCannonLegendary
                    ThermalScopedAssaultRifleLegendary
                    SuppressedAssaultRifleLegendary
                    SubmachineGunCLegendary
                    HeavySniperRifleLegendary
                    PumpShotgunLegendary
                    ScopedRevolverLegendary
                    SuppressedSniperRifleLegendary
                    BoomBowLegendary
            # Chapter 1, Season 9
            array:
                array:
                    AssaultRifleCommon
                    SemiAutoPistolCommon
                    SuppressedSubmachineGunCommon
                    TacticalShotgunCommon
                    FlintKnockPistolCommon
                    HeavyAssaultRifleCommon
                    DrumShotgunCommon
                    BurstSMGCommon
                    RevolverCommon
                array:
                    AssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SemiAutoPistolUncommon
                    SuppressedSubmachineGunUncommon
                    ScopedAssaultRifleUncommon
                    InfantryRifleUncommon
                    DrumGunUncommon
                    FlintKnockPistolUncommon
                    HeavyAssaultRifleUncommon
                    DrumShotgunUncommon
                    BurstSMGUncommon
                    RevolverUncommon
                array:
                    AssaultRifleRare
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    GrenadeLauncherRare
                    PumpShotgunRare
                    SuppressedSubmachineGunRare
                    SemiAutoSuppressedPistolRare
                    HeavyAssaultRifleRare
                    InfantryRifleRare
                    DrumGunRare
                    CombatShotgunRare
                    DrumShotgunRare
                    BurstSMGRare
                    RevolverRare
                    BoltActionSniperRifleRare
                array:
                    AssaultRifleBEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    HandCannonEpic
                    HeavySniperRifleEpic
                    InfantryRifleEpic
                    TacticalAssaultRifleEpic
                    TacticalShotgunEpic
                    CombatShotgunEpic
                    RevolverBEpic
                    StormScoutSniperRifleEpic
                    ProximityGrenadeLauncherEpic
                array:
                    AssaultRifleBLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    HandCannonLegendary
                    HeavySniperRifleLegendary
                    SuppressedSniperRifleLegendary
                    BoomBowLegendary
                    TacticalAssaultRifleLegendary
                    TacticalShotgunLegendary
                    CombatShotgunLegendary
                    RevolverBLegendary
                    BoltActionSniperRifleLegendary
                    StormScoutSniperRifleLegendary
                    ProximityGrenadeLauncherLegendary
            # Chapter 1, Season X
            array:
                array:
                    AssaultRifleCommon
                    SemiAutoPistolCommon
                    SuppressedSubmachineGunCommon
                    TacticalShotgunCommon
                    FlintKnockPistolCommon
                    HeavyAssaultRifleCommon
                    DrumShotgunCommon
                    RevolverCommon
                array:
                    AssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunUncommon
                    SemiAutoPistolUncommon
                    SuppressedSubmachineGunUncommon
                    ScopedAssaultRifleUncommon
                    InfantryRifleUncommon
                    DrumGunUncommon
                    FlintKnockPistolUncommon
                    HeavyAssaultRifleUncommon
                    DrumShotgunUncommon
                    RevolverUncommon
                    TacticalSubmachineGunUncommon
                array:
                    AssaultRifleRare
                    ScopedAssaultRifleRare
                    TacticalShotgunRare
                    GrenadeLauncherRare
                    PumpShotgunRare
                    SuppressedSubmachineGunRare
                    SemiAutoSuppressedPistolRare
                    HeavyAssaultRifleRare
                    InfantryRifleRare
                    DrumGunRare
                    CombatShotgunRare
                    DrumShotgunRare
                    RevolverRare
                    BoltActionSniperRifleRare
                    TacticalSubmachineGunRare
                array:
                    AssaultRifleBEpic
                    TacticalSubmachineGunEpic
                    BoltActionSniperRifleEpic
                    GrenadeLauncherEpic
                    RocketLauncherEpic
                    MinigunEpic
                    SemiAutoSuppressedPistolEpic
                    HandCannonEpic
                    HeavySniperRifleEpic
                    InfantryRifleEpic
                    TacticalShotgunEpic
                    CombatShotgunEpic
                    RevolverBEpic
                    ProximityGrenadeLauncherEpic
                    SuppressedAssaultRifleEpic
                    TacticalSubmachineGunEpic
                    AutomaticSniperRifleEpic
                array:
                    AssaultRifleBLegendary
                    GrenadeLauncherLegendary
                    RocketLauncherLegendary
                    MinigunLegendary
                    HandCannonLegendary
                    HeavySniperRifleLegendary
                    SuppressedSniperRifleLegendary
                    BoomBowLegendary
                    TacticalShotgunLegendary
                    CombatShotgunLegendary
                    RevolverBLegendary
                    BoltActionSniperRifleLegendary
                    ProximityGrenadeLauncherLegendary
                    SuppressedAssaultRifleLegendary
                    TacticalSubmachineGunLegendary
                    AutomaticSniperRifleLegendary
            # Chapter 2, Season 1
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleBCommon
                    HeavyAssaultRifleCommon
                    TacticalShotgunCommon
                    PumpShotgunBCommon
                    SubmachineGunBCommon
                    SemiAutoPistolCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    HeavyAssaultRifleUncommon
                    TacticalShotgunUncommon
                    PumpShotgunBUncommon
                    SubmachineGunBUncommon
                    SemiAutoPistolUncommon
                    BoltActionSniperRifleUncommon
                    RocketLauncherUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleBRare
                    HeavyAssaultRifleRare
                    TacticalShotgunRare
                    PumpShotgunBRare
                    SubmachineGunBRare
                    SemiAutoPistolRare
                    BoltActionSniperRifleRare
                    RocketLauncherRare
                array:
                    AssaultRifleBEpic
                    StrikerBurstRifleEpic
                    HeavyAssaultRifleEpic
                    TacticalShotgunEpic
                    PumpShotgunBEpic
                    SubmachineGunCEpic
                    SemiAutoPistolEpic
                    BoltActionSniperRifleEpic
                    RocketLauncherEpic
                array:
                    AssaultRifleBLegendary
                    StrikerBurstRifleLegendary
                    HeavyAssaultRifleLegendary
                    TacticalShotgunLegendary
                    PumpShotgunBLegendary
                    SubmachineGunCLegendary
                    SemiAutoPistolLegendary
                    BoltActionSniperRifleLegendary
                    RocketLauncherLegendary
            # Chapter 2, Season 2
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleBCommon
                    TacticalShotgunCommon
                    PumpShotgunBCommon
                    SubmachineGunBCommon
                    SemiAutoPistolCommon
                    SuppressedSubmachineGunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    TacticalShotgunUncommon
                    PumpShotgunBUncommon
                    SubmachineGunBUncommon
                    SemiAutoPistolUncommon
                    SuppressedSubmachineGunUncommon
                    RapidFireSMGUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleBRare
                    HeavyAssaultRifleRare
                    TacticalShotgunRare
                    PumpShotgunBRare
                    SubmachineGunBRare
                    SemiAutoPistolRare
                    SuppressedAssaultRifleRare
                    SuppressedSubmachineGunRare
                    RapidFireSMGRare
                array:
                    AssaultRifleBEpic
                    StrikerBurstRifleEpic
                    HeavyAssaultRifleEpic
                    TacticalShotgunEpic
                    PumpShotgunBEpic
                    SemiAutoPistolEpic
                    RocketLauncherEpic
                    SuppressedAssaultRifleEpic
                    SuppressedSniperRifleEpic
                    MinigunEpic
                    HeavySniperRifleEpic
                array:
                    AssaultRifleBLegendary
                    StrikerBurstRifleLegendary
                    HeavyAssaultRifleLegendary
                    TacticalShotgunLegendary
                    PumpShotgunBLegendary
                    SemiAutoPistolLegendary
                    RocketLauncherLegendary
                    SuppressedAssaultRifleLegendary
                    SuppressedSniperRifleLegendary
                    MinigunLegendary
                    HeavySniperRifleLegendary
                array:
                    SkyesAssaultRifleMythic
                    MeowsclesPeowPeowRifleMythic
                    BrutusMinigunMythic
                    TNTinasKaBoombow
                    ShadowMidasDrumGunMythic
            # Chapter 2, Season 3
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleBCommon
                    TacticalShotgunCommon
                    PumpShotgunBCommon
                    SubmachineGunBCommon
                    SemiAutoPistolCommon
                    SuppressedSubmachineGunCommon
                    RapidFireSMGCommon
                    ChargeShotgunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    TacticalShotgunUncommon
                    PumpShotgunBUncommon
                    SubmachineGunBUncommon
                    SemiAutoPistolUncommon
                    SuppressedSubmachineGunUncommon
                    RapidFireSMGUncommon
                    ChargeShotgunUncommon
                    HuntingRifleUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleBRare
                    TacticalShotgunRare
                    PumpShotgunBRare
                    SubmachineGunBRare
                    SemiAutoPistolRare
                    SuppressedAssaultRifleRare
                    SuppressedSubmachineGunRare
                    RapidFireSMGRare
                    ChargeShotgunRare
                    HuntingRifleRare
                    BoltActionSniperRifleRare
                array:
                    AssaultRifleBEpic
                    StrikerBurstRifleEpic
                    TacticalShotgunEpic
                    PumpShotgunBEpic
                    SemiAutoPistolEpic
                    RocketLauncherEpic
                    RapidFireSMGEpic
                    SubmachineGunCEpic
                    ChargeShotgunEpic
                    HuntingRifleEpic
                    BoltActionSniperRifleEpic
                array:
                    AssaultRifleBLegendary
                    StrikerBurstRifleLegendary
                    TacticalShotgunLegendary
                    PumpShotgunBLegendary
                    SemiAutoPistolLegendary
                    RocketLauncherLegendary
                    RapidFireSMGLegendary
                    SubmachineGunCLegendary
                    ChargeShotgunLegendary
                    HuntingRifleLegendary
                    BoltActionSniperRifleLegendary
                array:
                    KitsChargeShotgunMythic
                    OceansBurstAssaultRifleMythic
                    JulesDrumGunMythic
            # Chapter 2, Season 4
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleBCommon
                    PumpShotgunBCommon
                    SuppressedSubmachineGunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    PumpShotgunBUncommon
                    SuppressedSubmachineGunUncommon
                    TacticalSubmachineGunUncommon
                array:
                    LightMachineGunRare
                    AssaultRifleRare
                    BurstAssaultRifleRare
                    PumpShotgunBRare
                    CombatShotgunRare
                    TacticalSubmachineGunRare
                    SuppressedSubmachineGunRare
                    BoltActionSniperRifleRare
                array:
                    LightMachineGunEpic
                    AssaultRifleBEpic
                    StrikerBurstRifleEpic
                    ScopedAssaultRifleEpic
                    PumpShotgunBEpic
                    CombatShotgunEpic
                    TacticalSubmachineGunLegendary
                    RevolverBEpic
                    BoltActionSniperRifleEpic
                    RocketLauncherEpic
                array:
                    AssaultRifleBLegendary
                    StrikerBurstRifleLegendary
                    ScopedAssaultRifleLegendary
                    PumpShotgunBLegendary
                    CombatShotgunLegendary
                    TacticalSubmachineGunLegendary
                    RevolverBLegendary
                    BoltActionSniperRifleLegendary
                    RocketLauncherLegendary
            # Chapter 2, Season 5
            array:
                array:
                    AssaultRifleCommon
                    HeavyAssaultRifleCommon
                    TacticalShotgunCommon
                    LeverActionShotgunCommon
                    SuppressedSubmachineGunCommon
                    SubmachineGunBCommon
                    RapidFireSMGCommon
                    SemiAutoPistolCommon
                array:
                    AssaultRifleUncommon
                    HeavyAssaultRifleUncommon
                    ChargeShotgunUncommon
                    TacticalShotgunUncommon
                    LeverActionShotgunUncommon
                    SuppressedSubmachineGunUncommon
                    SubmachineGunBUncommon
                    RapidFireSMGCommon
                    SemiAutoPistolUncommon
                    LeverActionRifleUncommon
                array:
                    AssaultRifleRare
                    HeavyAssaultRifleRare
                    ChargeShotgunRare
                    TacticalShotgunRare
                    LeverActionShotgunRare
                    SuppressedSubmachineGunRare
                    RapidFireSMGRare
                    SubmachineGunBRare
                    SemiAutoPistolRare
                    BoltActionSniperRifleEpic
                    LeverActionRifleRare
                array:
                    AssaultRifleBEpic
                    HeavyAssaultRifleEpic
                    DragonsBreathShotgunEpic
                    ChargeShotgunEpic
                    TacticalShotgunEpic
                    LeverActionShotgunEpic
                    SubmachineGunCEpic
                    RapidFireSMGEpic
                    SemiAutoPistolEpic
                    BoltActionSniperRifleEpic
                    LeverActionRifleEpic
                    RocketLauncherEpic
                array:
                    AssaultRifleBLegendary
                    HeavyAssaultRifleLegendary
                    DragonsBreathShotgunLegendary
                    ChargeShotgunLegendary
                    TacticalShotgunLegendary
                    LeverActionShotgunLegendary
                    SubmachineGunCLegendary
                    RapidFireSMGLegendary
                    SemiAutoPistolLegendary
                    BoltActionSniperRifleLegendary
                    RocketLauncherLegendary
                array:
                    SkyesAssaultRifleMythic
                array:
                    BoomSniperRifleExotic
                    NightHawkExotic
                    ShadowTrackerExotic
                    StormScoutExotic
                    TheDubExotic
                    DragonsBreathSniperExotic
                    HopRockDualiesExotic
                    BurstQuadLauncherExotic
            # Chapter 2, Season 6
            array:
                array:
                    MakeshiftRifleCommon
                    MakeshiftShotgunCommon
                    MakeshiftSubmachineGunCommon
                    MakeshiftRevolverCommon
                array:
                    MakeshiftRifleUncommon
                    AssaultRifleUncommon
                    PrimalRifleUncommon
                    InfantryRifleUncommon
                    MakeshiftShotgunUncommon
                    PrimalShotgunUncommon
                    PumpShotgunBUncommon
                    TacticalShotgunUncommon
                    SubmachineGunBUncommon
                    PrimalSMGUncommon
                    MakeshiftSubmachineGunUncommon
                    MakeshiftRevolverUncommon
                    PrimalPistolUncommon
                    RevolverUncommon
                array:
                    MakeshiftRifleRare
                    AssaultRifleRare
                    PrimalRifleRare
                    InfantryRifleRare
                    PrimalShotgunRare
                    MakeshiftShotgunRare
                    PumpShotgunBRare
                    TacticalShotgunRare
                    MakeshiftSubmachineGunRare
                    SubmachineGunBRare
                    PrimalSMGRare
                    PrimalPistolRare
                    MakeshiftRevolverRare
                    RevolverRare
                    DualPistolsRare
                    RecyclerRare
                array:
                    AssaultRifleBEpic
                    PrimalRifleEpic
                    InfantryRifleEpic
                    PrimalShotgunEpic
                    PumpShotgunBEpic
                    TacticalShotgunEpic
                    SubmachineGunBEpic
                    PrimalSMGEpic
                    PrimalPistolEpic
                    RevolverBEpic
                    DualPistolsEpic
                    RecyclerEpic
                array:
                    AssaultRifleBLegendary
                    PrimalRifleLegendary
                    InfantryRifleLegendary
                    PrimalShotgunLegendary
                    PumpShotgunBLegendary
                    TacticalShotgunLegendary
                    SubmachineGunBLegendary
                    PrimalSMGLegendary
                    PrimalPistolLegendary
                    RevolverBLegendary
                    RecyclerLegendary
                array:
                    RazsExplosiveBowMythic
                array:
                    ShadowTrackerExotic
                    HopRockDualiesExotic
                    GrapplerBowExotic
                    UnstableBow
                    MarksmanSixShooterExotic
            # Chapter 2, Season 7
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleBCommon
                    HeavyAssaultRifleCommon
                    PumpShotgunBCommon
                    TacticalShotgunCommon
                    LeverActionShotgunCommon
                    SubmachineGunBCommon
                    RapidFireSMGCommon
                    SuppressedSubmachineGunCommon
                    SemiAutoPistolCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    HeavyAssaultRifleUncommon
                    PumpShotgunBUncommon
                    TacticalShotgunUncommon
                    LeverActionShotgunUncommon
                    SuppressedSubmachineGunUncommon
                    SubmachineGunBUncommon
                    RapidFireSMGUncommon
                    SemiAutoPistolUncommon
                array:
                    PulseRifleRare
                    RailGunRare
                    KymeraRayGunRare
                    AssaultRifleRare
                    BurstAssaultRifleBRare
                    HeavyAssaultRifleRare
                    PumpShotgunBRare
                    TacticalShotgunRare
                    LeverActionShotgunRare
                    SuppressedSubmachineGunRare
                    SubmachineGunBRare
                    RapidFireSMGRare
                    SemiAutoPistolRare
                    BoltActionSniperRifleRare
                array:
                    PulseRifleEpic
                    RailGunEpic
                    KymeraRayGunEpic
                    AssaultRifleBEpic
                    StrikerBurstRifleEpic
                    HeavyAssaultRifleEpic
                    PumpShotgunBEpic
                    TacticalShotgunEpic
                    LeverActionShotgunEpic
                    SubmachineGunCEpic
                    RapidFireSMGEpic
                    SemiAutoPistolEpic
                    HandCannonEpic
                    BoltActionSniperRifleEpic
                    RocketLauncherEpic
                array:
                    PulseRifleLegendary
                    RailGunLegendary
                    KymeraRayGunLegendary
                    AssaultRifleBLegendary
                    StrikerBurstRifleLegendary
                    HeavyAssaultRifleLegendary
                    PumpShotgunBLegendary
                    TacticalShotgunLegendary
                    LeverActionShotgunLegendary
                    SubmachineGunCLegendary
                    RapidFireSMGLegendary
                    SemiAutoPistolLegendary
                    HandCannonLegendary
                    BoltActionSniperRifleLegendary
                    RocketLauncherLegendary
                    PlasmaCannonLegendary
                array:
                    SlonesPulseRifleMythic
                    ZygAndChoppysRayGunMythic
                array:
                    ShadowTrackerExotic
                    MarksmanSixShooterExotic
                    StormScoutExotic
                    NightHawkExotic
                    BurstPulseRifleExotic
            # Chapter 2, Season 8
            array:
                array:
                    SidewaysRifleCommon
                    SidewaysMinigunCommon
                    SidewaysScytheCommon
                    AssaultRifleCommon
                    BurstAssaultRifleBCommon
                    CombatAssaultRifleCommon
                    PumpShotgunBCommon
                    LeverActionShotgunCommon
                    ChargeShotgunCommon
                    SubmachineGunBCommon
                    CombatPistolCommon
                    FlintKnockPistolCommon
                array:
                    SidewaysRifleUncommon
                    SidewaysMinigunUncommon
                    SidewaysScytheUncommon
                    AssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    CombatAssaultRifleUncommon
                    PumpShotgunBUncommon
                    LeverActionShotgunUncommon
                    ChargeShotgunUncommon
                    CombatShotgunUncommon
                    SubmachineGunBUncommon
                    CombatPistolUncommon
                    FlintKnockPistolUncommon
                array:
                    SidewaysRifleRare
                    SidewaysMinigunRare
                    SidewaysScytheRare
                    RailGunRare
                    RapidFireSMGRare
                    AssaultRifleRare
                    SuppressedAssaultRifleRare
                    BurstAssaultRifleBRare
                    CombatAssaultRifleRare
                    PumpShotgunBRare
                    LeverActionShotgunRare
                    ChargeShotgunRare
                    CombatShotgunRare
                    SubmachineGunBRare
                    CombatPistolRare
                    AutomaticSniperRifleRare
                    DualFiendHuntersRare
                array:
                    SidewaysRifleEpic
                    SidewaysMinigunEpic
                    SidewaysScytheEpic
                    RailGunEpic
                    AssaultRifleBEpic
                    SuppressedAssaultRifleEpic
                    StrikerBurstRifleEpic
                    CombatAssaultRifleEpic
                    PumpShotgunBEpic
                    LeverActionShotgunEpic
                    ChargeShotgunEpic
                    CombatShotgunEpic
                    SubmachineGunCEpic
                    CombatPistolEpic
                    AutomaticSniperRifleEpic
                    DualFiendHuntersEpic
                    RocketLauncherEpic
                array:
                    SidewaysRifleLegendary
                    SidewaysMinigunLegendary
                    SidewaysScytheLegendary
                    RailGunLegendary
                    AssaultRifleBLegendary
                    StrikerBurstRifleLegendary
                    CombatAssaultRifleLegendary
                    SuppressedAssaultRifleLegendary
                    PumpShotgunBLegendary
                    LeverActionShotgunLegendary
                    ChargeShotgunLegendary
                    CombatShotgunLegendary
                    SubmachineGunCLegendary
                    CombatPistolLegendary
                    AutomaticSniperRifleLegendary
                    DualFiendHuntersLegendary
                    RocketLauncherLegendary
                array:
                    SlonesBurstAssaultRifleMythic
                array:
                    ShadowTrackerExotic
                    DragonsBreathSniperExotic
                    MarksmanSixShooterExotic
            # Chapter 3, Season 1
            array:
                array:
                    MKSevenAssaultRifleCommon
                    RangerAssaultRifleCommon
                    StrikerPumpShotgunCommon
                    HeavyShotgunCommon
                    AutoShotgunCommon
                    StingerSMGCommon
                    MachineSMGCommon
                    SidearmPistolCommon
                array:
                    MKSevenAssaultRifleUncommon
                    RangerAssaultRifleUncommon
                    StrikerPumpShotgunUncommon
                    HeavyShotgunUncommon
                    AutoShotgunUncommon
                    StingerSMGUncommon
                    MachineSMGUncommon
                    SidearmPistolUncommon
                    HunterBoltActionSniperUncommon
                array:
                    MKSevenAssaultRifleRare
                    RangerAssaultRifleRare
                    StrikerPumpShotgunRare
                    HeavyShotgunRare
                    AutoShotgunRare
                    StingerSMGRare
                    MachineSMGRare
                    SidearmPistolRare
                    HunterBoltActionSniperRare
                array:
                    MKSevenAssaultRifleEpic
                    RangerAssaultRifleEpic
                    StrikerPumpShotgunEpic
                    HeavyShotgunEpic
                    AutoShotgunEpic
                    StingerSMGEpic
                    MachineSMGEpic
                    SidearmPistolEpic
                    HunterBoltActionSniperEpic
                    GrenadeLauncherEpic
                array:
                    MKSevenAssaultRifleLegendary
                    RangerAssaultRifleLegendary
                    StrikerPumpShotgunLegendary
                    HeavyShotgunLegendary
                    AutoShotgunLegendary
                    StingerSMGLegendary
                    MachineSMGLegendary
                    SidearmPistolLegendary
                    HunterBoltActionSniperLegendary
                    GrenadeLauncherLegendary
                array:
                    GunnarsStingerSMGMythic
                array:
                    ShadowTrackerExotic
                    TheDubExotic
                    BoomSniperRifleExotic
                    DragonsBreathSniperExotic
                    MarksmanSixShooterExotic
            # Chapter 3, Season 2
            array:
                array:
                    MKSevenAssaultRifleCommon
                    RangerAssaultRifleCommon
                    StrikerPumpShotgunCommon
                    AutoShotgunCommon
                    StingerSMGCommon
                    SidearmPistolCommon
                    StrikerBurstRifleCommon
                    LightMachineGunCommon
                    RangerShotgunCommon
                    DrumShotgunCommon
                    CombatSMGCommon
                    RevolverBCommon
                array:
                    MKSevenAssaultRifleUncommon
                    RangerAssaultRifleUncommon
                    StrikerPumpShotgunUncommon
                    AutoShotgunUncommon
                    StingerSMGUncommon
                    SidearmPistolUncommon
                    HunterBoltActionSniperUncommon
                    StrikerBurstRifleUncommon
                    LightMachineGunUncommon
                    RangerShotgunUncommon
                    DrumShotgunUncommon
                    CombatSMGUncommon
                    RevolverBUncommon
                array:
                    MKSevenAssaultRifleRare
                    RangerAssaultRifleRare
                    StrikerPumpShotgunRare
                    AutoShotgunRare
                    StingerSMGRare
                    SidearmPistolRare
                    HunterBoltActionSniperRare
                    StrikerBurstRifleRare
                    LightMachineGunRare
                    RangerShotgunRare
                    DrumShotgunRare
                    CombatSMGRare
                    RevolverBRare
                    AnvilRocketLauncherRare
                array:
                    MKSevenAssaultRifleEpic
                    RangerAssaultRifleEpic
                    StrikerPumpShotgunEpic
                    AutoShotgunEpic
                    StingerSMGEpic
                    SidearmPistolEpic
                    HunterBoltActionSniperEpic
                    GrenadeLauncherEpic
                    StrikerBurstRifleEpic
                    ThermalScopedAssaultRifleEpic
                    LightMachineGunEpic
                    RangerShotgunEpic
                    DrumShotgunEpic
                    CombatSMGEpic
                    RevolverBEpic
                    HeavySniperRifleEpic
                    AnvilRocketLauncherEpic
                array:
                    MKSevenAssaultRifleLegendary
                    RangerAssaultRifleLegendary
                    StrikerPumpShotgunLegendary
                    AutoShotgunLegendary
                    StingerSMGLegendary
                    SidearmPistolLegendary
                    HunterBoltActionSniperLegendary
                    GrenadeLauncherLegendary
                    StrikerBurstRifleLegendary
                    ThermalScopedAssaultRifleLegendary
                    LightMachineGunLegendary
                    RangerShotgunLegendary
                    DrumShotgunLegendary
                    CombatSMGLegendary
                    RevolverBLegendary
                    HeavySniperRifleLegendary
                    AnvilRocketLauncherLegendary
                array:
                    GunnarsStingerSMGMythic
                    HuntmasterSabersThermalRifleMythic
                    SlonesBurstAssaultRifleMythic
                array:
                    ShadowTrackerExotic
                    TheDubExotic
                    BoomSniperRifleExotic
                    DragonsBreathSniperExotic
                    MarksmanSixShooterExotic
                    NightHawkExotic
                    BoomSniperRifleExotic
                    StormScoutExotic
            # Chapter 3, Season 3
            array:
                array:
                    HammerAssaultRifleCommon
                    CombatAssaultRifleCommon
                    StrikerBurstRifleCommon
                    RangerAssaultRifleCommon
                    StrikerPumpShotgunCommon
                    TwoShotShotgunCommon
                    PrimeShotgunCommon
                    AutoShotgunCommon
                    StingerSMGCommon
                    ChargeSMGCommon
                    SidearmPistolCommon
                    RevolverCommon
                    DMRCommon
                array:
                    HammerAssaultRifleUncommon
                    CombatAssaultRifleUncommon
                    StrikerBurstRifleUncommon
                    RangerAssaultRifleUncommon
                    StrikerPumpShotgunUncommon
                    TwoShotShotgunUncommon
                    PrimeShotgunUncommon
                    AutoShotgunUncommon
                    StingerSMGUncommon
                    ChargeSMGUncommon
                    SidearmPistolUncommon
                    RevolverUncommon
                    DMRUncommon
                array:
                    HammerAssaultRifleRare
                    CombatAssaultRifleRare
                    StrikerBurstRifleRare
                    RangerAssaultRifleRare
                    StrikerPumpShotgunRare
                    TwoShotShotgunRare
                    PrimeShotgunRare
                    AutoShotgunRare
                    StingerSMGRare
                    ChargeSMGRare
                    SidearmPistolRare
                    RevolverRare
                    DMRRare
                array:
                    HammerAssaultRifleEpic
                    CombatAssaultRifleEpic
                    StrikerBurstRifleEpic
                    RangerAssaultRifleEpic
                    StrikerPumpShotgunEpic
                    TwoShotShotgunEpic
                    PrimeShotgunEpic
                    AutoShotgunEpic
                    StingerSMGEpic
                    ChargeSMGEpic
                    SidearmPistolEpic
                    RevolverEpic
                    DMREpic
                    HeavySniperRifleEpic
                array:
                    HammerAssaultRifleLegendary
                    CombatAssaultRifleLegendary
                    StrikerBurstRifleLegendary
                    RangerAssaultRifleLegendary
                    StrikerPumpShotgunLegendary
                    TwoShotShotgunLegendary
                    PrimeShotgunLegendary
                    AutoShotgunLegendary
                    StingerSMGLegendary
                    ChargeSMGLegendary
                    SidearmPistolLegendary
                    RevolverLegendary
                    DMRLegendary
                    HeavySniperRifleLegendary
                array:
                    HammerAssaultRifleMythic
                    TwoShotShotgunMythic
                    DMRMythic
                array:
                    ShadowTrackerExotic
                    TheDubExotic
                    BoomSniperRifleExotic
                    MarksmanSixShooterExotic
            # Chapter 3, Season 4
            array:
                array:
                    HammerAssaultRifleCommon
                    RangerAssaultRifleCommon
                    RangerShotgunCommon
                    PrimeShotgunCommon
                    LeverActionShotgunCommon
                    SuppressedSubmachineGunCommon
                    RapidFireSMGCommon
                    SidearmPistolCommon
                    CobraDMRCommon
                array:
                    EvoChromeBurstRifleUncommon
                    HammerAssaultRifleUncommon
                    RangerAssaultRifleUncommon
                    RangerShotgunUncommon
                    PrimeShotgunUncommon
                    LeverActionShotgunUncommon
                    EvoChromeShotgunUncommon
                    SuppressedSubmachineGunUncommon
                    RapidFireSMGUncommon
                    SidearmPistolUncommon
                    CobraDMRUncommon
                    HunterBoltActionSniperUncommon
                array:
                    EvoChromeBurstRifleRare
                    HammerAssaultRifleRare
                    RangerAssaultRifleRare
                    RangerShotgunRare
                    PrimeShotgunRare
                    LeverActionShotgunRare
                    EvoChromeShotgunRare
                    SuppressedSubmachineGunRare
                    RapidFireSMGRare
                    SidearmPistolRare
                    CobraDMRRare
                    HunterBoltActionSniperRare
                    ExplosiveGooGunRare
                array:
                    EvoChromeBurstRifleEpic
                    HammerAssaultRifleEpic
                    RangerAssaultRifleEpic
                    RangerShotgunEpic
                    PrimeShotgunEpic
                    LeverActionShotgunEpic
                    EvoChromeShotgunEpic
                    SuppressedSubmachineGunEpic
                    RapidFireSMGEpic
                    SidearmPistolEpic
                    CobraDMREpic
                    HunterBoltActionSniperEpic
                array:
                    EvoChromeBurstRifleLegendary
                    HammerAssaultRifleLegendary
                    RangerAssaultRifleLegendary
                    RangerShotgunLegendary
                    PrimeShotgunLegendary
                    LeverActionShotgunLegendary
                    EvoChromeShotgunLegendary
                    SuppressedSubmachineGunLegendary
                    RapidFireSMGLegendary
                    SidearmPistolLegendary
                    CobraDMRLegendary
                    HunterBoltActionSniperLegendary
                array:
                    InkquisitorsSuppressedSMGMythic
                    HammerAssaultRifleMythic
                    EvoChromeBurstRifleMythic
                    PrimeShotgunMythic
                    EvoChromeShotgunMythic
                    RapidFireSMGMythic
                    CobraDMRMythic
                array:
                    ShadowTrackerExotic
                    TheDubExotic
                    BoomSniperRifleExotic
            # Chapter 4, Season 1
            array:
                array:
                    AssaultRifleBCommon
                    RedEyeAssaultRifleCommon
                    BurstAssaultRifleBCommon
                    HeavyShotgunCommon
                    MavenAutoShotgunCommon
                    ThunderShotgunCommon
                    TwinMagSMGCommon
                    MachineSMGCommon
                    TacticalPistolCommon
                    DMRCommon
                array:
                    AssaultRifleBUncommon
                    RedEyeAssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    InfantryRifleUncommon
                    HeavyShotgunUncommon
                    MavenAutoShotgunUncommon
                    ThunderShotgunUncommon
                    TwinMagSMGUncommon
                    MachineSMGUncommon
                    TacticalPistolUncommon
                    SixShooterUncommon
                    DMRUncommon
                array:
                    AssaultRifleBRare
                    RedEyeAssaultRifleRare
                    BurstAssaultRifleBRare
                    InfantryRifleRare
                    CombatShotgunRare
                    HeavyShotgunRare
                    MavenAutoShotgunRare
                    ThunderShotgunRare
                    TwinMagSMGRare
                    MachineSMGRare
                    TacticalPistolRare
                    SixShooterRare
                    DMRRare
                    ExCaliberRifleRare
                    MechanicalShockwaveBowRare
                    MechanicalExplosiveBowRare
                    PrimalFlameBowRare
                    PrimalStinkBowRare
                array:
                    AssaultRifleBEpic
                    RedEyeAssaultRifleEpic
                    TacticalAssaultRifleEpic
                    BurstAssaultRifleBEpic
                    InfantryRifleEpic
                    HeavyShotgunEpic
                    MavenAutoShotgunEpic
                    ThunderShotgunEpic
                    TwinMagSMGEpic
                    MachineSMGEpic
                    TacticalPistolEpic
                    SixShooterEpic
                    DMREpic
                    ExCaliberRifleEpic
                    MechanicalShockwaveBowEpic
                    MechanicalExplosiveBowEpic
                    PrimalFlameBowEpic
                    PrimalStinkBowEpic
                    RocketLauncherEpic
                array:
                    AssaultRifleBLegendary
                    RedEyeAssaultRifleLegendary
                    TacticalAssaultRifleLegendary
                    BurstAssaultRifleBLegendary
                    InfantryRifleLegendary
                    HeavyShotgunLegendary
                    MavenAutoShotgunLegendary
                    ThunderShotgunLegendary
                    TwinMagSMGLegendary
                    MachineSMGLegendary
                    TacticalPistolLegendary
                    DMRLegendary
                    ExCaliberRifleLegendary
                    MechanicalShockwaveBowLegendary
                    MechanicalExplosiveBowLegendary
                    PrimalFlameBowLegendary
                    PrimalStinkBowLegendary
                    RocketLauncherLegendary
                array:
                    TheAgelessChampionsExCaliberRifleMythic
                    TheAgelessChampionsShockwaveHammerMythic
                    TacticalPistolMythic
                array:
                    ShadowTrackerExotic
                    TheDubExotic
                    GrapplerBowExotic
                    UnstableBow
            # Chapter 4, Season 2
            array:
                array:
                    RedEyeAssaultRifleCommon
                    HavocSuppressedAssaultRifleCommon
                    HavocPumpShotgunCommon
                    CombatShotgunCommon
                    MavenAutoShotgunCommon
                    SubmachineGunBCommon
                    TwinMagSMGCommon
                    TacticalPistolCommon
                    CobraDMRCommon
                array:
                    CombatShotgunUncommon
                    MavenAutoShotgunUncommon
                    SubmachineGunBUncommon
                    TwinMagSMGUncommon
                    TacticalPistolUncommon
                    FlintKnockPistolUncommon
                    CobraDMRUncommon
                array:
                    CombatShotgunRare
                    MavenAutoShotgunRare
                    SubmachineGunBRare
                    TwinMagSMGRare
                    TacticalPistolRare
                    LockOnPistolRare
                    CobraDMRRare
                    TwinMagSMGRare
                    KineticBladeRare
                array:
                    ChargeShotgunEpic
                    CombatShotgunEpic
                    MavenAutoShotgunEpic
                    SubmachineGunBEpic
                    TwinMagSMGEpic
                    TacticalPistolEpic
                    CobraDMREpic
                    HeavySniperRifleEpic
                    KineticBladeEpic
                array:
                    ChargeShotgunLegendary
                    CombatShotgunLegendary
                    MavenAutoShotgunLegendary
                    SubmachineGunBLegendary
                    TwinMagSMGLegendary
                    TacticalPistolLegendary
                    CobraDMRLegendary
                    HeavySniperRifleLegendary
                array:
                    HighcardsHavocSuppressedRifleMythic
                    EnhancedHavocShotgunMythic
                    OverclockedPulseRifleMythic
                    TacticalPistolMythic
                array:
                    ShadowTrackerExotic
                    DragonsBreathSniperExotic
                    HeistedExplosiveAssaultRifleExotic
                    HeistedAccelerantShotgunExotic
                    HeistedBreacherShotgunExotic
                    HeistedBlinkMagSMGExotic
                    HeistedRunNGunSMGExotic
            # Chapter 4, Season 3
            array:
                array:
                    MKAlphaAssaultRifleCommon
                    FlapjackRifleCommon
                    HavocSuppressedAssaultRifleCommon
                    HavocPumpShotgunCommon
                    LeverActionShotgunCommon
                    MavenAutoShotgunCommon
                    DrumShotgunCommon
                    SubmachineGunBCommon
                    CombatSMGCommon
                    TacticalPistolCommon
                    MammothPistolCommon
                    ThermalDMRCommon
                array:
                    MKAlphaAssaultRifleUncommon
                    FlapjackRifleUncommon
                    HavocSuppressedAssaultRifleUncommon
                    HavocPumpShotgunUncommon
                    LeverActionShotgunUncommon
                    MavenAutoShotgunUncommon
                    DrumShotgunUncommon
                    SubmachineGunBUncommon
                    CombatSMGUncommon
                    TacticalPistolUncommon
                    MammothPistolUncommon
                    ThermalDMRUncommon
                    SharpToothShotgunUncommon
                    ExplosiveRepeaterRifleUncommon
                array:
                    MKAlphaAssaultRifleRare
                    FlapjackRifleRare
                    HavocSuppressedAssaultRifleRare
                    HavocPumpShotgunRare
                    LeverActionShotgunRare
                    MavenAutoShotgunRare
                    DrumShotgunRare
                    SubmachineGunBRare
                    CombatSMGRare
                    TacticalPistolRare
                    MammothPistolRare
                    ThermalDMRRare
                    SharpToothShotgunRare
                    ExplosiveRepeaterRifleRare
                array:
                    MKAlphaAssaultRifleEpic
                    FlapjackRifleEpic
                    HavocSuppressedAssaultRifleEpic
                    HavocPumpShotgunEpic
                    LeverActionShotgunEpic
                    MavenAutoShotgunEpic
                    DrumShotgunEpic
                    SubmachineGunBEpic
                    CombatSMGEpic
                    TacticalPistolEpic
                    MammothPistolEpic
                    ThermalDMREpic
                    SharpToothShotgunEpic
                    ExplosiveRepeaterRifleEpic
                    DragonsBreathShotgunEpic
                    KineticBoomerangEpic
                    KineticBladeEpic
                array:
                    MKAlphaAssaultRifleLegendary
                    FlapjackRifleLegendary
                    HavocSuppressedAssaultRifleLegendary
                    HavocPumpShotgunLegendary
                    LeverActionShotgunLegendary
                    MavenAutoShotgunLegendary
                    DrumShotgunLegendary
                    SubmachineGunBLegendary
                    CombatSMGLegendary
                    TacticalPistolLegendary
                    MammothPistolLegendary
                    ThermalDMRLegendary
                    SharpToothShotgunLegendary
                    ExplosiveRepeaterRifleLegendary
                array:
                    HighcardsHavocSuppressedRifleMythic
                    EnhancedFlapJackRifleMythic
                    ReliksMKAlphaAssaultRifleMythic
                    EnhancedDrumShotgunMythic
                array:
                    ShadowTrackerExotic
                    DragonsBreathSniperExotic
                    HeistedExplosiveAssaultRifleExotic
                    HeistedAccelerantShotgunExotic
                    HeistedBreacherShotgunExotic
                    HeistedBlinkMagSMGExotic
                    HeistedRunNGunSMGExotic
            # Chapter 4, Season 4
            array:
                array:
                    TwinMagAssaultRifleCommon
                    HavocSuppressedAssaultRifleCommon
                    InfiltratorPumpShotgunCommon
                    MavenAutoShotgunCommon
                    CombatSMGCommon
                    ScopedBurstSMGCommon
                    SuppressedPistolCommon
                    ThermalDMRCommon
                array:
                    TwinMagAssaultRifleUncommon
                    HavocSuppressedAssaultRifleUncommon
                    InfiltratorPumpShotgunUncommon
                    MavenAutoShotgunUncommon
                    CombatSMGUncommon
                    ScopedBurstSMGUncommon
                    SuppressedPistolUncommon
                    ThermalDMRUncommon
                    TacticalDMRUncommon
                    SharpToothShotgunUncommon
                array:
                    TwinMagAssaultRifleRare
                    HavocSuppressedAssaultRifleRare
                    InfiltratorPumpShotgunRare
                    MavenAutoShotgunRare
                    CombatSMGRare
                    ScopedBurstSMGRare
                    SuppressedPistolRare
                    ThermalDMRRare
                    TacticalDMRRare
                    SharpToothShotgunRare
                    WoodStakeShotgunRare
                    SuppressedSniperRifleRare
                    PumpkinLauncherRare
                array:
                    TwinMagAssaultRifleEpic
                    HavocSuppressedAssaultRifleEpic
                    InfiltratorPumpShotgunEpic
                    MavenAutoShotgunEpic
                    CombatSMGEpic
                    ScopedBurstSMGEpic
                    SuppressedPistolEpic
                    ThermalDMREpic
                    TacticalDMREpic
                    SharpToothShotgunEpic
                    WoodStakeShotgunEpic
                    SuppressedSniperRifleEpic
                    StickyGrenadeLauncherEpic
                    PumpkinLauncherEpic
                    KineticBladeEpic
                array:
                    TwinMagAssaultRifleLegendary
                    HavocSuppressedAssaultRifleLegendary
                    InfiltratorPumpShotgunLegendary
                    MavenAutoShotgunLegendary
                    CombatSMGLegendary
                    ScopedBurstSMGLegendary
                    SuppressedPistolLegendary
                    ThermalDMRLegendary
                    TacticalDMRLegendary
                    SharpToothShotgunLegendary
                    WoodStakeShotgunLegendary
                    SuppressedSniperRifleLegendary
                    StickyGrenadeLauncherLegendary
                    PumpkinLauncherLegendary
                array:
                    ShadowMidasDrumGunMythic
                    ThornesVampiricBladeMythic
                    HeartsHavocSuppressedRifleMythic
                    GunnarsStingerSMGMythic
                    KitsChargeShotgunMythic
                    TNTinasKaBoombow
                    ZygAndChoppysRayGunMythic
                    DiamondsThermalDMRMythic
                    EnhancedInfiltratorPumpShotgunMythic
                array:
                    HeistedExplosiveAssaultRifleExotic
                    HeistedAccelerantShotgunExotic
                    HeistedBreacherShotgunExotic
                    HeistedBlinkMagSMGExotic
                    HeistedRunNGunSMGExotic
                    ShadowTrackerExotic
            # Chapter 4, Season OG
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleBCommon
                    PumpShotgunBCommon
                    TacticalShotgunCommon
                    SubmachineGunBCommon
                    SuppressedSubmachineGunCommon
                    PistolCommon
                    FlintKnockPistolCommon
                    HeavyAssaultRifleCommon
                    DrumShotgunCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    ScopedAssaultRifleUncommon
                    PumpShotgunBUncommon
                    TacticalShotgunUncommon
                    SubmachineGunBUncommon
                    SuppressedSubmachineGunUncommon
                    PistolUncommon
                    HuntingRifleUncommon
                    DrumGunUncommon
                    TacticalSubmachineGunUncommon
                    FlintKnockPistolUncommon
                    HeavyAssaultRifleUncommon
                    SixShooterUncommon
                    InfantryRifleUncommon
                    DrumShotgunUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleBRare
                    ScopedAssaultRifleRare
                    LightMachineGunRare
                    PumpShotgunBRare
                    TacticalShotgunRare
                    SubmachineGunBRare
                    SuppressedSubmachineGunRare
                    PistolRare
                    BoltActionSniperRifleRare
                    HuntingRifleRare
                    RocketLauncherRare
                    GrenadeLauncherRare
                    DrumGunRare
                    CombatShotgunRare
                    TacticalSubmachineGunRare
                    DualPistolsRare
                    SuppressedSniperRifleRare
                    HeavyAssaultRifleRare
                    SixShooterRare
                    InfantryRifleRare
                    DrumShotgunRare
                array:
                    AssaultRifleBEpic
                    BurstAssaultRifleBEpic
                    SuppressedAssaultRifleEpic
                    ScopedAssaultRifleEpic
                    LightMachineGunEpic
                    PumpShotgunBEpic
                    TacticalShotgunEpic
                    HeavyShotgunEpic
                    SubmachineGunCEpic
                    HandCannonEpic
                    SemiAutoSniperRifleEpic
                    BoltActionSniperRifleEpic
                    HuntingRifleEpic
                    RocketLauncherEpic
                    GrenadeLauncherEpic
                    MinigunEpic
                    CombatShotgunEpic
                    TacticalSubmachineGunEpic
                    DualPistolsEpic
                    SuppressedSniperRifleEpic
                    QuadLauncherEpic
                    HeavyAssaultRifleEpic
                    DoubleBarrelEpic
                    SixShooterEpic
                    InfantryRifleEpic
                    DrumShotgunEpic
                    HeavySniperRifleEpic
                    ProximityGrenadeLauncherEpic
                array:
                    AssaultRifleBLegendary
                    BurstAssaultRifleBLegendary
                    SuppressedAssaultRifleLegendary
                    ScopedAssaultRifleLegendary
                    PumpShotgunBLegendary
                    TacticalShotgunLegendary
                    HeavyShotgunLegendary
                    SubmachineGunCLegendary
                    HandCannonLegendary
                    SemiAutoSniperRifleLegendary
                    BoltActionSniperRifleLegendary
                    HuntingRifleLegendary
                    RocketLauncherLegendary
                    GrenadeLauncherLegendary
                    MinigunLegendary
                    CombatShotgunLegendary
                    DualPistolsLegendary
                    TacticalSubmachineGunLegendary
                    SuppressedSniperRifleLegendary
                    QuadLauncherLegendary
                    HeavyAssaultRifleLegendary
                    DoubleBarrelLegendary
                    InfantryRifleLegendary
                    DrumShotgunLegendary
                    HeavySniperRifleLegendary
                    ProximityGrenadeLauncherLegendary
            # Chapter 5, Season 1
            array:
                array:
                    ModularNemesisARCommon
                    ModularStrikerARCommon
                    ModularEnforcerARCommon
                    ModularHammerPumpShotgunCommon
                    ModularFrenzyAutoShotgunCommon
                    ModularThunderBurstSMGCommon
                    ModularHyperSMGCommon
                    ModularRangerPistolCommon
                array:
                    ModularThunderBurstSMGUncommon
                    ModularNemesisARUncommon
                    ModularStrikerARUncommon
                    ModularEnforcerARUncommon
                    ModularHammerPumpShotgunUncommon
                    ModularFrenzyAutoShotgunUncommon
                    ReaperModularSniperRifleUncommon
                    ModularHyperSMGUncommon
                    ModularRangerPistolUncommon
                array:
                    ModularThunderBurstSMGRare
                    ModularNemesisARRare
                    ModularStrikerARRare
                    ModularEnforcerARRare
                    ModularHammerPumpShotgunRare
                    ReaperModularSniperRifleRare
                    LockOnPistolRare
                    AnvilRocketLauncherRare
                    ModularHyperSMGRare
                    ModularRangerPistolRare
                    ModularFrenzyAutoShotgunRare
                array:
                    ModularThunderBurstSMGEpic
                    ModularNemesisAREpic
                    ModularStrikerAREpic
                    ModularEnforcerAREpic
                    ModularHammerPumpShotgunEpic
                    ReaperModularSniperRifleEpic
                    BallisticShieldEpic
                    GrappleBladeEpic
                    AnvilRocketLauncherEpic
                    SnowballLauncherEpic
                    ModularHyperSMGEpic
                    ModularRangerPistolEpic
                    ModularFrenzyAutoShotgunEpic
                array:
                    ModularThunderBurstSMGLegendary
                    ModularNemesisARLegendary
                    ModularStrikerARLegendary
                    ModularEnforcerARLegendary
                    ModularHammerPumpShotgunLegendary
                    ReaperModularSniperRifleLegendary
                    AnvilRocketLauncherLegendary
                    ModularHyperSMGLegendary
                    ModularRangerPistolLegendary
                    ModularFrenzyAutoShotgunLegendary
                array:
                    MontaguesModularNemesisARMythic
                    NishasModularStrikerARMythic
                    OscarsModularFrenzyAutoShotgunMythic
                    ValeriasModularHyperSMGMythic
            # Chapter 5, Season 2
            array:
                array:
                    ModularThunderBurstSMGCommon
                    ModularNemesisARCommon
                    ModularHammerPumpShotgunCommon
                    ModularFrenzyAutoShotgunCommon
                    ModularThunderBurstSMGCommon
                    ModularRangerPistolCommon
                    ModularTacticalAssaultRifleCommon
                    ModularWarforgedAssaultRifleCommon
                    ModularHarbingerSMGCommon
                array:
                    ModularThunderBurstSMGUncommon
                    ModularNemesisARUncommon
                    ModularHammerPumpShotgunUncommon
                    ModularFrenzyAutoShotgunUncommon
                    ModularRangerPistolUncommon
                    ModularTacticalAssaultRifleUncommon
                    ModularHuntressDMRUncommon
                    ModularTacticalAssaultRifleUncommon
                    ModularWarforgedAssaultRifleUncommon
                    ModularGatekeeperShotgunUncommon
                    ModularHarbingerSMGUncommon
                array:
                    ModularThunderBurstSMGRare
                    ModularNemesisARRare
                    ModularHammerPumpShotgunRare
                    ReaperModularSniperRifleRare
                    ModularRangerPistolRare
                    ModularDrumGunRare
                    ModularTacticalAssaultRifleRare
                    ModularHuntressDMRRare
                    ModularTacticalAssaultRifleRare
                    ModularWarforgedAssaultRifleRare
                    ModularGatekeeperShotgunRare
                    ModularHarbingerSMGRare
                    ModularFrenzyAutoShotgunRare
                array:
                    ModularThunderBurstSMGEpic
                    ModularNemesisAREpic
                    ModularHammerPumpShotgunEpic
                    ReaperModularSniperRifleEpic
                    ModularRangerPistolEpic
                    ModularDrumGunEpic
                    ChainsOfHadesEpic
                    ModularTacticalAssaultRifleEpic
                    ModularHuntressDMREpic
                    ModularTacticalAssaultRifleEpic
                    ModularWarforgedAssaultRifleEpic
                    ModularGatekeeperShotgunEpic
                    ModularHarbingerSMGEpic
                    ModularFrenzyAutoShotgunEpic
                array:
                    ModularThunderBurstSMGLegendary
                    ModularNemesisARLegendary
                    ModularHammerPumpShotgunLegendary
                    ReaperModularSniperRifleLegendary
                    ModularRangerPistolLegendary
                    ModularDrumGunLegendary
                    ModularTacticalAssaultRifleLegendary
                    ModularHuntressDMRLegendary
                    ModularTacticalAssaultRifleLegendary
                    ModularWarforgedAssaultRifleLegendary
                    ModularGatekeeperShotgunLegendary
                    ModularHarbingerSMGLegendary
                    ModularFrenzyAutoShotgunLegendary
                array:
                    MidasModularDrumGunMythic
                    AresModularWarforgedAssaultRifle
                    ModularZeusHuntressDMRMythic
                    CerberusModularGatekeeperShotgun
                    HadesModularHarbingerSMGMythic
            # Chapter 5, Season 3
            array:
                array:
                    ModularHammerPumpShotgunCommon
                    ModularThunderBurstSMGCommon
                    ModularRangerPistolCommon
                    ModularTacticalAssaultRifleCommon
                    ModularWarforgedAssaultRifleCommon
                    ModularHarbingerSMGCommon
                    ModularCombatShotgunCommon
                    ModularEnforcerARCommon
                    ModularCombatAssaultRifleCommon
                    PistolCommon
                array:
                    ModularThunderBurstSMGUncommon
                    ModularHammerPumpShotgunUncommon
                    ModularRangerPistolUncommon
                    ModularTacticalAssaultRifleUncommon
                    ModularHuntressDMRUncommon
                    ModularTacticalAssaultRifleUncommon
                    ModularWarforgedAssaultRifleUncommon
                    ModularGatekeeperShotgunUncommon
                    ModularHarbingerSMGUncommon
                    FlintKnockPistolUncommon
                    ModularCombatShotgunUncommon
                    ModularEnforcerARUncommon
                    ModularCombatAssaultRifleUncommon
                array:
                    ModularThunderBurstSMGRare
                    ModularHammerPumpShotgunRare
                    ModularRangerPistolRare
                    ModularTacticalAssaultRifleRare
                    ModularHuntressDMRRare
                    ModularTacticalAssaultRifleRare
                    ModularWarforgedAssaultRifleRare
                    ModularGatekeeperShotgunRare
                    ModularHarbingerSMGRare
                    TowHookCannonRare
                    MinigunRare
                    HeavyImpactSniperRifleRare
                    ModularCombatShotgunRare
                    ModularEnforcerARRare
                    ModularCombatAssaultRifleRare
                    ModularHandCannonRare
                    ModularBoomBoltRare
                array:
                    ModularThunderBurstSMGEpic
                    ModularHammerPumpShotgunEpic
                    ModularRangerPistolEpic
                    ChainsOfHadesEpic
                    ModularTacticalAssaultRifleEpic
                    ModularHuntressDMREpic
                    ModularTacticalAssaultRifleEpic
                    ModularWarforgedAssaultRifleEpic
                    ModularGatekeeperShotgunEpic
                    ModularHarbingerSMGEpic
                    HeavyImpactSniperRifleEpic
                    ModularCombatShotgunEpic
                    ModularEnforcerAREpic
                    ModularCombatAssaultRifleEpic
                    ModularHandCannonEpic
                    ModularBoomBoltEpic
                array:
                    ModularThunderBurstSMGLegendary
                    ModularHammerPumpShotgunLegendary
                    ModularRangerPistolLegendary
                    ModularTacticalAssaultRifleLegendary
                    ModularHuntressDMRLegendary
                    ModularTacticalAssaultRifleLegendary
                    ModularWarforgedAssaultRifleLegendary
                    ModularGatekeeperShotgunLegendary
                    ModularHarbingerSMGLegendary
                    HeavyImpactSniperRifleLegendary
                    ModularCombatShotgunLegendary
                    ModularEnforcerARLegendary
                    ModularCombatAssaultRifleLegendary
                    ModularHandCannonLegendary
                    ModularBoomBoltLegendary
                array:
                    TheMachinistsModularCombatAssaultRifleMythic
                    MegaloDonsModularCombatShotgunMythic
                    ModularConductorHandCannonMythic
                    RingmastersModularBoomBoltMythic
                    MegaloDonsNitroFistsMythic
                    OscarsModularFrenzyAutoShotgunMythic
            # Chapter 5, Season 4
            array:
                array:
                    ModularHammerPumpShotgunCommon
                    ModularRangerPistolCommon
                    ModularWarforgedAssaultRifleCommon
                    ModularStrikerBurstRifleCommon
                    ModularSovereignShotgunCommon
                    DualMicroSMGsCommon
                    ModularMonarchPistolCommon
                array:
                    ModularHammerPumpShotgunUncommon
                    ModularRangerPistolUncommon
                    ModularTacticalAssaultRifleUncommon
                    ModularWarforgedAssaultRifleUncommon
                    ModularGatekeeperShotgunUncommon
                    ModularStrikerBurstRifleUncommon
                    ModularSovereignShotgunUncommon
                    DualMicroSMGsUncommon
                    ModularMonarchPistolUncommon
                array:
                    ModularHammerPumpShotgunRare
                    ModularRangerPistolRare
                    ModularTacticalAssaultRifleRare
                    ModularWarforgedAssaultRifleRare
                    ModularGatekeeperShotgunRare
                    PumpkinLauncherRare
                    WoodStakeShotgunRare
                    ModularStrikerBurstRifleRare
                    ModularSovereignShotgunRare
                    DualMicroSMGsRare
                    ModularMonarchPistolRare
                array:
                    ModularHammerPumpShotgunEpic
                    ModularRangerPistolEpic
                    ChainsOfHadesEpic
                    ModularTacticalAssaultRifleEpic
                    ModularWarforgedAssaultRifleEpic
                    ModularGatekeeperShotgunEpic
                    Chainsaw
                    PumpkinLauncherEpic
                    WoodStakeShotgunEpic
                    ModularStrikerBurstRifleEpic
                    ModularSovereignShotgunEpic
                    DualMicroSMGsEpic
                    ModularMonarchPistolEpic
                array:
                    ModularHammerPumpShotgunLegendary
                    ModularRangerPistolLegendary
                    ModularTacticalAssaultRifleLegendary
                    ModularWarforgedAssaultRifleLegendary
                    ModularGatekeeperShotgunLegendary
                    PumpkinLauncherLegendary
                    WoodStakeShotgunLegendary
                    ModularStrikerBurstRifleLegendary
                    ModularSovereignShotgunLegendary
                    DualMicroSMGsLegendary
                    ModularMonarchPistolLegendary
            # Chapter 5, Remix
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleBCommon
                    PumpShotgunBCommon
                    TacticalShotgunCommon
                    SubmachineGunBCommon
                    SemiAutoPistolCommon
                    BoltActionSniperRifleCommon
                    SuppressedSubmachineGunCommon
                    HeavyAssaultRifleCommon
                    RapidFireSMGCommon
                    SuppressedPistolCommon
                    ChargeShotgunCommon
                array:
                    DrumGunUncommon
                    AssaultRifleUncommon
                    BurstAssaultRifleBUncommon
                    PumpShotgunBUncommon
                    TacticalShotgunUncommon
                    SubmachineGunBUncommon
                    SemiAutoPistolUncommon
                    SemiAutoSniperRifleUncommon
                    BoltActionSniperRifleUncommon
                    SuppressedSubmachineGunUncommon
                    HeavyAssaultRifleUncommon
                    RapidFireSMGUncommon
                    TacticalSubmachineGunUncommon
                    SuppressedPistolUncommon
                    HuntingRifleUncommon
                    ChargeShotgunUncommon
                array:
                    SuppressedAssaultRifleRare
                    ScopedAssaultRifleRare
                    DrumGunRare
                    AssaultRifleRare
                    BurstAssaultRifleBRare
                    PumpShotgunBRare
                    TacticalShotgunRare
                    SubmachineGunBRare
                    SemiAutoPistolRare
                    SemiAutoSniperRifleRare
                    RocketLauncherRare
                    BoltActionSniperRifleRare
                    SuppressedSubmachineGunRare
                    TacticalAssaultRifleRare
                    HeavyAssaultRifleRare
                    RapidFireSMGRare
                    TacticalSubmachineGunRare
                    SuppressedPistolRare
                    HuntingRifleRare
                    ChargeShotgunRare
                array:
                    ScopedAssaultRifleEpic
                    AssaultRifleBEpic
                    StrikerBurstRifleEpic
                    PumpShotgunBEpic
                    TacticalShotgunEpic
                    SubmachineGunCEpic
                    SemiAutoPistolEpic
                    DualPistolsEpic
                    HeavySniperRifleEpic
                    BoltActionSniperRifleEpic
                    RocketLauncherEpic
                    BurstAssaultRifleBEpic
                    MinigunEpic
                    GrenadeLauncherEpic
                    TacticalAssaultRifleEpic
                    HeavyAssaultRifleEpic
                    HeavyShotgunEpic
                    RapidFireSMGEpic
                    TacticalSubmachineGunEpic
                    SuppressedPistolEpic
                    HuntingRifleEpic
                    SuppressedSniperRifleEpic
                    ChargeShotgunEpic
                    HandCannonEpic
                    ScopedRevolverEpic
                    ProximityGrenadeLauncherEpic
                array:
                    ScopedAssaultRifleLegendary
                    AssaultRifleBEpic
                    StrikerBurstRifleEpic
                    PumpShotgunBLegendary
                    TacticalShotgunLegendary
                    SubmachineGunCLegendary
                    SemiAutoPistolLegendary
                    DualPistolsLegendary
                    HeavySniperRifleLegendary
                    BoltActionSniperRifleLegendary
                    RocketLauncherLegendary
                    BurstAssaultRifleBLegendary
                    MinigunLegendary
                    GrenadeLauncherLegendary
                    TacticalAssaultRifleLegendary
                    HeavyAssaultRifleLegendary
                    HeavyShotgunLegendary
                    RapidFireSMGLegendary
                    TacticalSubmachineGunLegendary
                    SuppressedPistolLegendary
                    HuntingRifleLegendary
                    SuppressedSniperRifleLegendary
                    ChargeShotgunLegendary
                    HandCannonLegendary
                    ScopedRevolverLegendary
                    ProximityGrenadeLauncherLegendary
                array:
                    TNTinasKaBoombow
                    KitsChargeShotgunMythic
            # Chapter 6, Season 1
            array:
                array:
                    ModularThunderBurstSMGCommon
                    HoloTwisterAssaultRifleCommon
                    FuryAssaultRifleCommon
                    SentinelPumpShotgunCommon
                    TwinfireAutoShotgunCommon
                    OniShotgunCommon
                    VeiledPrecisionSMGCommon
                    SurgefireSMGCommon
                    SuppressedPistolCommon
                array:
                    HoloTwisterAssaultRifleUncommon
                    FuryAssaultRifleUncommon
                    SentinelPumpShotgunUncommon
                    TwinfireAutoShotgunUncommon
                    OniShotgunUncommon
                    VeiledPrecisionSMGUncommon
                    SurgefireSMGUncommon
                    SuppressedPistolUncommon
                    HuntingRifleBUncommon
                array:
                    HoloTwisterAssaultRifleRare
                    FuryAssaultRifleRare
                    SentinelPumpShotgunRare
                    TwinfireAutoShotgunRare
                    OniShotgunRare
                    VeiledPrecisionSMGRare
                    SurgefireSMGRare
                    SuppressedPistolRare
                    HuntingRifleBRare
                array:
                    HoloTwisterAssaultRifleEpic
                    FuryAssaultRifleEpic
                    SentinelPumpShotgunEpic
                    TwinfireAutoShotgunEpic
                    OniShotgunEpic
                    VeiledPrecisionSMGEpic
                    SurgefireSMGEpic
                    SuppressedPistolEpic
                    HuntingRifleEpic
                    TyphoonBladeEpic
                array:
                    HoloTwisterAssaultRifleLegendary
                    FuryAssaultRifleLegendary
                    SentinelPumpShotgunLegendary
                    TwinfireAutoShotgunLegendary
                    OniShotgunLegendary
                    VeiledPrecisionSMGLegendary
                    SurgefireSMGLegendary
                    SuppressedPistolLegendary
                    HuntingRifleLegendary
                array:
                    EnhancedHoloTwisterAssaultRifleMythic
                    EnhancedFuryAssaultRifleMythic
                    EnhancedSentinelPumpShotgunMythic
                    EnhancedTwinfireAutoShotgunMythic
                    EnhancedOniShotgunMythic
                    NightRoseVeiledPrecisionSMGMythic
                    EnhancedSurgefireSMGMythic
                    TyphoonBladeMythic
                    HuntingRifleBMythic
            # Fortnite OG, Season 1
            array:
                array:
                    AssaultRifleCommon
                    BurstAssaultRifleCommon
                    PumpShotgunCommon
                    TacticalShotgunCommon
                    SubmachineGunCommon
                    RevolverCommon
                    SemiAutoPistolCommon
                array:
                    AssaultRifleUncommon
                    BurstAssaultRifleUncommon
                    TacticalSubmachineGunUncommon
                    PumpShotgunUncommon
                    TacticalShotgunUncommon
                    SubmachineGunUncommon
                    RevolverUncommon
                    SemiAutoPistolUncommon
                array:
                    AssaultRifleRare
                    BurstAssaultRifleRare
                    ScopedAssaultRifleRare
                    BoltActionSniperRifleRare
                    RocketLauncherRare
                    GrenadeLauncherRare
                    TacticalShotgunRare
                    SubmachineGunRare
                    RevolverRare
                    SemiAutoPistolRare
                array:
                    AssaultRifleEpic
                    BurstAssaultRifleEpic
                    ScopedAssaultRifleEpic
                    BoltActionSniperRifleEpic
                    SemiAutoSniperRifleEpic
                    RocketLauncherEpic
                    GrenadeLauncherEpic
                array:
                    SemiAutoSniperRifleLegendary
                    BoltActionSniperRifleLegendary
                    AssaultRifleBLegendary
                    BurstAssaultRifleLegendary
                    RocketLauncherLegendary
                    GrenadeLauncherLegendary

    item_ids := module:
        AnvilRocketLauncherRare<public>: int = 0
        AnvilRocketLauncherEpic<public>: int = 1
        AnvilRocketLauncherLegendary<public>: int = 2
        AresModularWarforgedAssaultRifle<public>: int = 3
        AssaultRifleCommon<public>: int = 4
        AssaultRifleUncommon<public>: int = 5
        AssaultRifleRare<public>: int = 6
        AssaultRifleEpic<public>: int = 7
        AssaultRifleLegendary<public>: int = 8
        AssaultRifleBCommon<public>: int = 9
        AssaultRifleBUncommon<public>: int = 10
        AssaultRifleBRare<public>: int = 11
        AssaultRifleBEpic<public>: int = 12
        AssaultRifleBLegendary<public>: int = 13
        AutoShotgunCommon<public>: int = 14
        AutoShotgunUncommon<public>: int = 15
        AutoShotgunRare<public>: int = 16
        AutoShotgunEpic<public>: int = 17
        AutoShotgunLegendary<public>: int = 18
        AutoShotgunMythic<public>: int = 19
        AutomaticSniperRifleUncommon<public>: int = 20
        AutomaticSniperRifleRare<public>: int = 21
        AutomaticSniperRifleEpic<public>: int = 22
        AutomaticSniperRifleLegendary<public>: int = 23
        BallisticShieldEpic<public>: int = 24
        BasicHammerCommon<public>: int = 25
        BoltActionSniperRifleCommon<public>: int = 26
        BoltActionSniperRifleUncommon<public>: int = 27
        BoltActionSniperRifleRare<public>: int = 28
        BoltActionSniperRifleEpic<public>: int = 29
        BoltActionSniperRifleLegendary<public>: int = 30
        BoomBowLegendary<public>: int = 31
        BoomSniperRifleExotic<public>: int = 32
        BrutusMinigunMythic<public>: int = 33
        BurstAssaultRifleCommon<public>: int = 34
        BurstAssaultRifleUncommon<public>: int = 35
        BurstAssaultRifleRare<public>: int = 36
        BurstAssaultRifleEpic<public>: int = 37
        BurstAssaultRifleLegendary<public>: int = 38
        BurstAssaultRifleBCommon<public>: int = 39
        BurstAssaultRifleBUncommon<public>: int = 40
        BurstAssaultRifleBRare<public>: int = 41
        BurstAssaultRifleBEpic<public>: int = 42
        BurstAssaultRifleBLegendary<public>: int = 43
        BurstPulseRifleExotic<public>: int = 44
        BurstQuadLauncherExotic<public>: int = 45
        BurstSMGCommon<public>: int = 46
        BurstSMGUncommon<public>: int = 47
        BurstSMGRare<public>: int = 48
        CerberusModularGatekeeperShotgun<public>: int = 49
        ChainsOfHadesEpic<public>: int = 50
        Chainsaw<public>: int = 51
        ChargeShotgunCommon<public>: int = 52
        ChargeShotgunUncommon<public>: int = 53
        ChargeShotgunRare<public>: int = 54
        ChargeShotgunEpic<public>: int = 55
        ChargeShotgunLegendary<public>: int = 56
        ChargeSMGCommon<public>: int = 57
        ChargeSMGUncommon<public>: int = 58
        ChargeSMGRare<public>: int = 59
        ChargeSMGEpic<public>: int = 60
        ChargeSMGLegendary<public>: int = 61
        ChargeSMGMythic<public>: int = 62
        CobraDMRCommon<public>: int = 63
        CobraDMRUncommon<public>: int = 64
        CobraDMRRare<public>: int = 65
        CobraDMREpic<public>: int = 66
        CobraDMRLegendary<public>: int = 67
        CobraDMRMythic<public>: int = 68
        CombatAssaultRifleCommon<public>: int = 69
        CombatAssaultRifleUncommon<public>: int = 70
        CombatAssaultRifleRare<public>: int = 71
        CombatAssaultRifleEpic<public>: int = 72
        CombatAssaultRifleLegendary<public>: int = 73
        CombatPistolCommon<public>: int = 74
        CombatPistolUncommon<public>: int = 75
        CombatPistolRare<public>: int = 76
        CombatPistolEpic<public>: int = 77
        CombatPistolLegendary<public>: int = 78
        CombatShotgunCommon<public>: int = 79
        CombatShotgunUncommon<public>: int = 80
        CombatShotgunRare<public>: int = 81
        CombatShotgunEpic<public>: int = 82
        CombatShotgunLegendary<public>: int = 83
        CombatSMGCommon<public>: int = 84
        CombatSMGUncommon<public>: int = 85
        CombatSMGRare<public>: int = 86
        CombatSMGEpic<public>: int = 87
        CombatSMGLegendary<public>: int = 88
        CombatSMGMythic<public>: int = 89
        CrossbowRare<public>: int = 90
        CrossbowEpic<public>: int = 91
        CupidsCrossbowEpic<public>: int = 92
        DiamondsThermalDMRMythic<public>: int = 93
        DMRCommon<public>: int = 94
        DMRUncommon<public>: int = 95
        DMRRare<public>: int = 96
        DMREpic<public>: int = 97
        DMRLegendary<public>: int = 98
        DMRMythic<public>: int = 99
        DoubleBarrelEpic<public>: int = 100
        DoubleBarrelLegendary<public>: int = 101
        DragonsBreathShotgunEpic<public>: int = 102
        DragonsBreathShotgunLegendary<public>: int = 103
        DragonsBreathSniperExotic<public>: int = 104
        DrumGunUncommon<public>: int = 105
        DrumGunRare<public>: int = 106
        DrumShotgunCommon<public>: int = 107
        DrumShotgunUncommon<public>: int = 108
        DrumShotgunRare<public>: int = 109
        DrumShotgunEpic<public>: int = 110
        DrumShotgunLegendary<public>: int = 111
        DualFiendHuntersCommon<public>: int = 112
        DualFiendHuntersUncommon<public>: int = 113
        DualFiendHuntersRare<public>: int = 114
        DualFiendHuntersEpic<public>: int = 115
        DualFiendHuntersLegendary<public>: int = 116
        DualMicroSMGsCommon<public>: int = 117
        DualMicroSMGsUncommon<public>: int = 118
        DualMicroSMGsRare<public>: int = 119
        DualMicroSMGsEpic<public>: int = 120
        DualMicroSMGsLegendary<public>: int = 121
        DualPistolsUncommon<public>: int = 122
        DualPistolsRare<public>: int = 123
        DualPistolsEpic<public>: int = 124
        DualPistolsLegendary<public>: int = 125
        DualSuppressedPistolsUncommon<public>: int = 126
        DualSuppressedPistolsRare<public>: int = 127
        DualSuppressedPistolsEpic<public>: int = 128
        DualSuppressedPistolsLegendary<public>: int = 129
        EggLauncherUncommon<public>: int = 130
        EggLauncherRare<public>: int = 131
        EggLauncherEpic<public>: int = 132
        EggLauncherLegendary<public>: int = 133
        EnhancedDrumShotgunMythic<public>: int = 134
        EnhancedFlapJackRifleMythic<public>: int = 135
        EnhancedFuryAssaultRifleMythic<public>: int = 136
        EnhancedHavocShotgunMythic<public>: int = 137
        EnhancedHoloTwisterAssaultRifleMythic<public>: int = 138
        EnhancedInfiltratorPumpShotgunMythic<public>: int = 139
        EnhancedOniShotgunMythic<public>: int = 140
        EnhancedSentinelPumpShotgunMythic<public>: int = 141
        EnhancedSurgefireSMGMythic<public>: int = 142
        EnhancedTwinfireAutoShotgunMythic<public>: int = 143
        EvoChromeBurstRifleCommon<public>: int = 144
        EvoChromeBurstRifleUncommon<public>: int = 145
        EvoChromeBurstRifleRare<public>: int = 146
        EvoChromeBurstRifleEpic<public>: int = 147
        EvoChromeBurstRifleLegendary<public>: int = 148
        EvoChromeBurstRifleMythic<public>: int = 149
        EvoChromeShotgunCommon<public>: int = 150
        EvoChromeShotgunUncommon<public>: int = 151
        EvoChromeShotgunRare<public>: int = 152
        EvoChromeShotgunEpic<public>: int = 153
        EvoChromeShotgunLegendary<public>: int = 154
        EvoChromeShotgunMythic<public>: int = 155
        ExCaliberRifleCommon<public>: int = 156
        ExCaliberRifleUncommon<public>: int = 157
        ExCaliberRifleRare<public>: int = 158
        ExCaliberRifleEpic<public>: int = 159
        ExCaliberRifleLegendary<public>: int = 160
        ExplosiveGooGunRare<public>: int = 161
        ExplosiveRepeaterRifleCommon<public>: int = 162
        ExplosiveRepeaterRifleUncommon<public>: int = 163
        ExplosiveRepeaterRifleRare<public>: int = 164
        ExplosiveRepeaterRifleEpic<public>: int = 165
        ExplosiveRepeaterRifleLegendary<public>: int = 166
        ExplosiveRepeaterRifleMythic<public>: int = 167
        FiendHunterCrossbowEpic<public>: int = 168
        FireOniMaskEpic<public>: int = 169
        FireworkFlareGunRare<public>: int = 170
        FlapjackRifleCommon<public>: int = 171
        FlapjackRifleUncommon<public>: int = 172
        FlapjackRifleRare<public>: int = 173
        FlapjackRifleEpic<public>: int = 174
        FlapjackRifleLegendary<public>: int = 175
        FlareGunRare<public>: int = 176
        FlashlightPistolRare<public>: int = 177
        FlintKnockPistolCommon<public>: int = 178
        FlintKnockPistolUncommon<public>: int = 179
        FuryAssaultRifleCommon<public>: int = 180
        FuryAssaultRifleUncommon<public>: int = 181
        FuryAssaultRifleRare<public>: int = 182
        FuryAssaultRifleEpic<public>: int = 183
        FuryAssaultRifleLegendary<public>: int = 184
        GrappleBladeEpic<public>: int = 185
        GrapplerBowExotic<public>: int = 186
        GrenadeLauncherRare<public>: int = 187
        GrenadeLauncherEpic<public>: int = 188
        GrenadeLauncherLegendary<public>: int = 189
        GunnarsStingerSMGMythic<public>: int = 190
        HadesModularHarbingerSMGMythic<public>: int = 191
        HammerAssaultRifleCommon<public>: int = 192
        HammerAssaultRifleUncommon<public>: int = 193
        HammerAssaultRifleRare<public>: int = 194
        HammerAssaultRifleEpic<public>: int = 195
        HammerAssaultRifleLegendary<public>: int = 196
        HammerAssaultRifleMythic<public>: int = 197
        HandCannonRare<public>: int = 198
        HandCannonEpic<public>: int = 199
        HandCannonLegendary<public>: int = 200
        HavocPumpShotgunCommon<public>: int = 201
        HavocPumpShotgunUncommon<public>: int = 202
        HavocPumpShotgunRare<public>: int = 203
        HavocPumpShotgunEpic<public>: int = 204
        HavocPumpShotgunLegendary<public>: int = 205
        HavocSuppressedAssaultRifleCommon<public>: int = 206
        HavocSuppressedAssaultRifleUncommon<public>: int = 207
        HavocSuppressedAssaultRifleRare<public>: int = 208
        HavocSuppressedAssaultRifleEpic<public>: int = 209
        HavocSuppressedAssaultRifleLegendary<public>: int = 210
        HavocSuppressedAssaultRifleMythic<public>: int = 211
        HeartsHavocSuppressedRifleMythic<public>: int = 212
        HeavyAssaultRifleCommon<public>: int = 213
        HeavyAssaultRifleUncommon<public>: int = 214
        HeavyAssaultRifleRare<public>: int = 215
        HeavyAssaultRifleEpic<public>: int = 216
        HeavyAssaultRifleLegendary<public>: int = 217
        HeavyImpactSniperRifleRare<public>: int = 218
        HeavyImpactSniperRifleEpic<public>: int = 219
        HeavyImpactSniperRifleLegendary<public>: int = 220
        HeavyShotgunCommon<public>: int = 221
        HeavyShotgunUncommon<public>: int = 222
        HeavyShotgunRare<public>: int = 223
        HeavyShotgunEpic<public>: int = 224
        HeavyShotgunLegendary<public>: int = 225
        HeavySniperRifleEpic<public>: int = 226
        HeavySniperRifleLegendary<public>: int = 227
        HeavySniperRifleMythic<public>: int = 228
        HeistedAccelerantShotgunExotic<public>: int = 229
        HeistedBlinkMagSMGExotic<public>: int = 230
        HeistedBreacherShotgunExotic<public>: int = 231
        HeistedExplosiveAssaultRifleExotic<public>: int = 232
        HeistedRunNGunSMGExotic<public>: int = 233
        HighStakesShotgunMythic<public>: int = 234
        HighcardsHavocSuppressedRifleMythic<public>: int = 235
        HoloTwisterAssaultRifleCommon<public>: int = 236
        HoloTwisterAssaultRifleUncommon<public>: int = 237
        HoloTwisterAssaultRifleRare<public>: int = 238
        HoloTwisterAssaultRifleEpic<public>: int = 239
        HoloTwisterAssaultRifleLegendary<public>: int = 240
        HopRockDualiesExotic<public>: int = 241
        HunterBoltActionSniperCommon<public>: int = 242
        HunterBoltActionSniperUncommon<public>: int = 243
        HunterBoltActionSniperRare<public>: int = 244
        HunterBoltActionSniperEpic<public>: int = 245
        HunterBoltActionSniperLegendary<public>: int = 246
        HuntingRifleUncommon<public>: int = 247
        HuntingRifleRare<public>: int = 248
        HuntingRifleEpic<public>: int = 249
        HuntingRifleLegendary<public>: int = 250
        HuntmasterSabersThermalRifleMythic<public>: int = 251
        InfantryRifleCommon<public>: int = 252
        InfantryRifleUncommon<public>: int = 253
        InfantryRifleRare<public>: int = 254
        InfantryRifleEpic<public>: int = 255
        InfantryRifleLegendary<public>: int = 256
        InfiltratorPumpShotgunCommon<public>: int = 257
        InfiltratorPumpShotgunUncommon<public>: int = 258
        InfiltratorPumpShotgunRare<public>: int = 259
        InfiltratorPumpShotgunEpic<public>: int = 260
        InfiltratorPumpShotgunLegendary<public>: int = 261
        InfinityBlade<public>: int = 262
        InkquisitorsSuppressedSMGMythic<public>: int = 263
        JulesDrumGunMythic<public>: int = 264
        KineticBladeRare<public>: int = 265
        KineticBladeEpic<public>: int = 266
        KineticBoomerangEpic<public>: int = 267
        KitsChargeShotgunMythic<public>: int = 268
        KitsShockwaveLauncherMythic<public>: int = 269
        KymeraRayGunRare<public>: int = 270
        KymeraRayGunEpic<public>: int = 271
        KymeraRayGunLegendary<public>: int = 272
        LeverActionRifleUncommon<public>: int = 273
        LeverActionRifleRare<public>: int = 274
        LeverActionRifleEpic<public>: int = 275
        LeverActionRifleLegendary<public>: int = 276
        LeverActionShotgunCommon<public>: int = 277
        LeverActionShotgunUncommon<public>: int = 278
        LeverActionShotgunRare<public>: int = 279
        LeverActionShotgunEpic<public>: int = 280
        LeverActionShotgunLegendary<public>: int = 281
        LightMachineGunCommon<public>: int = 282
        LightMachineGunUncommon<public>: int = 283
        LightMachineGunRare<public>: int = 284
        LightMachineGunEpic<public>: int = 285
        LightMachineGunLegendary<public>: int = 286
        LockOnPistolRare<public>: int = 287
        MachineSMGCommon<public>: int = 288
        MachineSMGUncommon<public>: int = 289
        MachineSMGRare<public>: int = 290
        MachineSMGEpic<public>: int = 291
        MachineSMGLegendary<public>: int = 292
        MakeshiftBowUncommon<public>: int = 293
        MakeshiftRevolverCommon<public>: int = 294
        MakeshiftRevolverUncommon<public>: int = 295
        MakeshiftRevolverRare<public>: int = 296
        MakeshiftSubmachineGunCommon<public>: int = 297
        MakeshiftSubmachineGunUncommon<public>: int = 298
        MakeshiftSubmachineGunRare<public>: int = 299
        MammothPistolCommon<public>: int = 300
        MammothPistolUncommon<public>: int = 301
        MammothPistolRare<public>: int = 302
        MammothPistolEpic<public>: int = 303
        MammothPistolLegendary<public>: int = 304
        MarksmanSixShooterExotic<public>: int = 305
        MavenAutoShotgunCommon<public>: int = 306
        MavenAutoShotgunUncommon<public>: int = 307
        MavenAutoShotgunRare<public>: int = 308
        MavenAutoShotgunEpic<public>: int = 309
        MavenAutoShotgunLegendary<public>: int = 310
        MechanicalBowRare<public>: int = 311
        MechanicalExplosiveBowRare<public>: int = 312
        MechanicalExplosiveBowEpic<public>: int = 313
        MechanicalExplosiveBowLegendary<public>: int = 314
        MechanicalShockwaveBowRare<public>: int = 315
        MechanicalShockwaveBowEpic<public>: int = 316
        MechanicalShockwaveBowLegendary<public>: int = 317
        MegaloDonsModularCombatShotgunMythic<public>: int = 318
        MegaloDonsNitroFistsMythic<public>: int = 319
        MeowsclesPeowPeowRifleMythic<public>: int = 320
        MidasModularDrumGunMythic<public>: int = 321
        MinigunRare<public>: int = 322
        MinigunEpic<public>: int = 323
        MinigunLegendary<public>: int = 324
        MKAlphaAssaultRifleCommon<public>: int = 325
        MKAlphaAssaultRifleUncommon<public>: int = 326
        MKAlphaAssaultRifleRare<public>: int = 327
        MKAlphaAssaultRifleEpic<public>: int = 328
        MKAlphaAssaultRifleLegendary<public>: int = 329
        MKSevenAssaultRifleCommon<public>: int = 330
        MKSevenAssaultRifleUncommon<public>: int = 331
        MKSevenAssaultRifleRare<public>: int = 332
        MKSevenAssaultRifleEpic<public>: int = 333
        MKSevenAssaultRifleLegendary<public>: int = 334
        ModularBoomBoltRare<public>: int = 335
        ModularBoomBoltEpic<public>: int = 336
        ModularBoomBoltLegendary<public>: int = 337
        ModularCombatAssaultRifleCommon<public>: int = 338
        ModularCombatAssaultRifleUncommon<public>: int = 339
        ModularCombatAssaultRifleRare<public>: int = 340
        ModularCombatAssaultRifleEpic<public>: int = 341
        ModularCombatAssaultRifleLegendary<public>: int = 342
        ModularCombatShotgunCommon<public>: int = 343
        ModularCombatShotgunUncommon<public>: int = 344
        ModularCombatShotgunRare<public>: int = 345
        ModularCombatShotgunEpic<public>: int = 346
        ModularCombatShotgunLegendary<public>: int = 347
        ModularConductorHandCannonMythic<public>: int = 348
        ModularDrumGunRare<public>: int = 349
        ModularDrumGunEpic<public>: int = 350
        ModularDrumGunLegendary<public>: int = 351
        ModularEnforcerARCommon<public>: int = 352
        ModularEnforcerARUncommon<public>: int = 353
        ModularEnforcerARRare<public>: int = 354
        ModularEnforcerAREpic<public>: int = 355
        ModularEnforcerARLegendary<public>: int = 356
        ModularFrenzyAutoShotgunCommon<public>: int = 357
        ModularFrenzyAutoShotgunUncommon<public>: int = 358
        ModularFrenzyAutoShotgunRare<public>: int = 359
        ModularFrenzyAutoShotgunEpic<public>: int = 360
        ModularFrenzyAutoShotgunLegendary<public>: int = 361
        ModularGatekeeprShotgunCommon<public>: int = 362
        ModularGatekeeperShotgunUncommon<public>: int = 363
        ModularGatekeeperShotgunRare<public>: int = 364
        ModularGatekeeperShotgunEpic<public>: int = 365
        ModularGatekeeperShotgunLegendary<public>: int = 366
        ModularHammerPumpShotgunCommon<public>: int = 367
        ModularHammerPumpShotgunUncommon<public>: int = 368
        ModularHammerPumpShotgunRare<public>: int = 369
        ModularHammerPumpShotgunEpic<public>: int = 370
        ModularHammerPumpShotgunLegendary<public>: int = 371
        ModularHandCannonRare<public>: int = 372
        ModularHandCannonEpic<public>: int = 373
        ModularHandCannonLegendary<public>: int = 374
        ModularHarbingerSMGCommon<public>: int = 375
        ModularHarbingerSMGUncommon<public>: int = 376
        ModularHarbingerSMGRare<public>: int = 377
        ModularHarbingerSMGEpic<public>: int = 378
        ModularHarbingerSMGLegendary<public>: int = 379
        ModularHuntressDMRUncommon<public>: int = 380
        ModularHuntressDMRRare<public>: int = 381
        ModularHuntressDMREpic<public>: int = 382
        ModularHuntressDMRLegendary<public>: int = 383
        ModularHyperSMGCommon<public>: int = 384
        ModularHyperSMGUncommon<public>: int = 385
        ModularHyperSMGRare<public>: int = 386
        ModularHyperSMGEpic<public>: int = 387
        ModularHyperSMGLegendary<public>: int = 388
        ModularMonarchPistolCommon<public>: int = 389
        ModularMonarchPistolUncommon<public>: int = 390
        ModularMonarchPistolRare<public>: int = 391
        ModularMonarchPistolEpic<public>: int = 392
        ModularMonarchPistolLegendary<public>: int = 393
        ModularNemesisARCommon<public>: int = 394
        ModularNemesisARUncommon<public>: int = 395
        ModularNemesisARRare<public>: int = 396
        ModularNemesisAREpic<public>: int = 397
        ModularNemesisARLegendary<public>: int = 398
        ModularRangerPistolCommon<public>: int = 399
        ModularRangerPistolUncommon<public>: int = 400
        ModularRangerPistolRare<public>: int = 401
        ModularRangerPistolEpic<public>: int = 402
        ModularRangerPistolLegendary<public>: int = 403
        ModularSovereignShotgunCommon<public>: int = 404
        ModularSovereignShotgunUncommon<public>: int = 405
        ModularSovereignShotgunRare<public>: int = 406
        ModularSovereignShotgunEpic<public>: int = 407
        ModularSovereignShotgunLegendary<public>: int = 408
        ModularStrikerARCommon<public>: int = 409
        ModularStrikerARUncommon<public>: int = 410
        ModularStrikerARRare<public>: int = 411
        ModularStrikerAREpic<public>: int = 412
        ModularStrikerARLegendary<public>: int = 413
        ModularStrikerBurstRifleCommon<public>: int = 414
        ModularStrikerBurstRifleUncommon<public>: int = 415
        ModularStrikerBurstRifleRare<public>: int = 416
        ModularStrikerBurstRifleEpic<public>: int = 417
        ModularStrikerBurstRifleLegendary<public>: int = 418
        ModularTacticalAssaultRifleCommon<public>: int = 419
        ModularTacticalAssaultRifleUncommon<public>: int = 420
        ModularTacticalAssaultRifleRare<public>: int = 421
        ModularTacticalAssaultRifleEpic<public>: int = 422
        ModularTacticalAssaultRifleLegendary<public>: int = 423
        ModularThunderBurstSMGCommon<public>: int = 424
        ModularThunderBurstSMGUncommon<public>: int = 425
        ModularThunderBurstSMGRare<public>: int = 426
        ModularThunderBurstSMGEpic<public>: int = 427
        ModularThunderBurstSMGLegendary<public>: int = 428
        ModularWarforgedAssaultRifleCommon<public>: int = 429
        ModularWarforgedAssaultRifleUncommon<public>: int = 430
        ModularWarforgedAssaultRifleRare<public>: int = 431
        ModularWarforgedAssaultRifleEpic<public>: int = 432
        ModularWarforgedAssaultRifleLegendary<public>: int = 433
        ModularZeusHuntressDMRMythic<public>: int = 434
        MontaguesModularNemesisARMythic<public>: int = 435
        NightHawkExotic<public>: int = 436
        NightRoseVeiledPrecisionSMGMythic<public>: int = 437
        NishasModularStrikerARMythic<public>: int = 438
        NitroFistsEpic<public>: int = 439
        OceansBurstAssaultRifleMythic<public>: int = 440
        OniShotgunCommon<public>: int = 441
        OniShotgunUncommon<public>: int = 442
        OniShotgunRare<public>: int = 443
        OniShotgunEpic<public>: int = 444
        OniShotgunLegendary<public>: int = 445
        OrangePaintLauncherRare<public>: int = 446
        OscarsModularFrenzyAutoShotgunMythic<public>: int = 447
        OverclockedPulseRifleMythic<public>: int = 448
        PistolCommon<public>: int = 449
        PistolUncommon<public>: int = 450
        PistolRare<public>: int = 451
        PlasmaCannonLegendary<public>: int = 452
        PrimalBowRare<public>: int = 453
        PrimalFlameBowRare<public>: int = 454
        PrimalFlameBowEpic<public>: int = 455
        PrimalFlameBowLegendary<public>: int = 456
        PrimalPistolUncommon<public>: int = 457
        PrimalPistolRare<public>: int = 458
        PrimalPistolEpic<public>: int = 459
        PrimalPistolLegendary<public>: int = 460
        PrimalRifleUncommon<public>: int = 461
        PrimalRifleRare<public>: int = 462
        PrimalRifleEpic<public>: int = 463
        PrimalRifleLegendary<public>: int = 464
        PrimalShotgunUncommon<public>: int = 465
        PrimalShotgunRare<public>: int = 466
        PrimalShotgunEpic<public>: int = 467
        PrimalShotgunLegendary<public>: int = 468
        PrimalSMGUncommon<public>: int = 469
        PrimalSMGRare<public>: int = 470
        PrimalSMGEpic<public>: int = 471
        PrimalSMGLegendary<public>: int = 472
        PrimalStinkBowRare<public>: int = 473
        PrimalStinkBowEpic<public>: int = 474
        PrimalStinkBowLegendary<public>: int = 475
        PrimeShotgunCommon<public>: int = 476
        PrimeShotgunUncommon<public>: int = 477
        PrimeShotgunRare<public>: int = 478
        PrimeShotgunEpic<public>: int = 479
        PrimeShotgunLegendary<public>: int = 480
        PrimeShotgunMythic<public>: int = 481
        ProximityGrenadeLauncherEpic<public>: int = 482
        ProximityGrenadeLauncherLegendary<public>: int = 483
        PulseRifleRare<public>: int = 484
        PulseRifleEpic<public>: int = 485
        PulseRifleLegendary<public>: int = 486
        PumpShotgunCommon<public>: int = 487
        PumpShotgunUncommon<public>: int = 488
        PumpShotgunRare<public>: int = 489
        PumpShotgunEpic<public>: int = 490
        PumpShotgunLegendary<public>: int = 491
        PumpShotgunBCommon<public>: int = 492
        PumpShotgunBUncommon<public>: int = 493
        PumpShotgunBRare<public>: int = 494
        PumpShotgunBEpic<public>: int = 495
        PumpShotgunBLegendary<public>: int = 496
        PumpkinLauncherUncommon<public>: int = 497
        PumpkinLauncherRare<public>: int = 498
        PumpkinLauncherEpic<public>: int = 499
        PumpkinLauncherLegendary<public>: int = 500
        PurplePaintLauncherRare<public>: int = 501
        QuadLauncherEpic<public>: int = 502
        QuadLauncherLegendary<public>: int = 503
        RailGunRare<public>: int = 504
        RailGunEpic<public>: int = 505
        RailGunLegendary<public>: int = 506
        RangerAssaultRifleCommon<public>: int = 507
        RangerAssaultRifleUncommon<public>: int = 508
        RangerAssaultRifleRare<public>: int = 509
        RangerAssaultRifleEpic<public>: int = 510
        RangerAssaultRifleLegendary<public>: int = 511
        RangerAssaultRifleMythic<public>: int = 512
        RangerShotgunCommon<public>: int = 513
        RangerShotgunUncommon<public>: int = 514
        RangerShotgunRare<public>: int = 515
        RangerShotgunEpic<public>: int = 516
        RangerShotgunLegendary<public>: int = 517
        RapidFireSMGCommon<public>: int = 518
        RapidFireSMGUncommon<public>: int = 519
        RapidFireSMGRare<public>: int = 520
        RapidFireSMGEpic<public>: int = 521
        RapidFireSMGLegendary<public>: int = 522
        RapidFireSMGMythic<public>: int = 523
        RazsExplosiveBowMythic<public>: int = 524
        ReaperModularSniperRifleUncommon<public>: int = 525
        ReaperModularSniperRifleRare<public>: int = 526
        ReaperModularSniperRifleEpic<public>: int = 527
        ReaperModularSniperRifleLegendary<public>: int = 528
        ReconScannerRare<public>: int = 529
        RecyclerRare<public>: int = 530
        RecyclerEpic<public>: int = 531
        RecyclerLegendary<public>: int = 532
        RedEyeAssaultRifleCommon<public>: int = 533
        RedEyeAssaultRifleUncommon<public>: int = 534
        RedEyeAssaultRifleRare<public>: int = 535
        RedEyeAssaultRifleEpic<public>: int = 536
        RedEyeAssaultRifleLegendary<public>: int = 537
        ReliksMKAlphaAssaultRifleMythic<public>: int = 538
        RevolverCommon<public>: int = 539
        RevolverUncommon<public>: int = 540
        RevolverRare<public>: int = 541
        RevolverEpic<public>: int = 542
        RevolverLegendary<public>: int = 543
        RevolverBCommon<public>: int = 544
        RevolverBUncommon<public>: int = 545
        RevolverBRare<public>: int = 546
        RevolverBEpic<public>: int = 547
        RevolverBLegendary<public>: int = 548
        RingmastersModularBoomBoltMythic<public>: int = 549
        RipsawLauncherRare<public>: int = 550
        RocketLauncherCommon<public>: int = 551
        RocketLauncherUncommon<public>: int = 552
        RocketLauncherRare<public>: int = 553
        RocketLauncherEpic<public>: int = 554
        RocketLauncherLegendary<public>: int = 555
        RocketRamRare<public>: int = 556
        ScopedAssaultRifleUncommon<public>: int = 557
        ScopedAssaultRifleRare<public>: int = 558
        ScopedAssaultRifleEpic<public>: int = 559
        ScopedAssaultRifleLegendary<public>: int = 560
        ScopedBurstSMGCommon<public>: int = 561
        ScopedBurstSMGUncommon<public>: int = 562
        ScopedBurstSMGRare<public>: int = 563
        ScopedBurstSMGEpic<public>: int = 564
        ScopedBurstSMGLegendary<public>: int = 565
        ScopedRevolverEpic<public>: int = 566
        ScopedRevolverLegendary<public>: int = 567
        SemiAutoPistolCommon<public>: int = 568
        SemiAutoPistolUncommon<public>: int = 569
        SemiAutoPistolRare<public>: int = 570
        SemiAutoPistolEpic<public>: int = 571
        SemiAutoPistolLegendary<public>: int = 572
        SemiAutoSniperRifleUncommon<public>: int = 573
        SemiAutoSniperRifleRare<public>: int = 574
        SemiAutoSniperRifleEpic<public>: int = 575
        SemiAutoSniperRifleLegendary<public>: int = 576
        SemiAutoSuppressedPistolUncommon<public>: int = 577
        SemiAutoSuppressedPistolRare<public>: int = 578
        SemiAutoSuppressedPistolEpic<public>: int = 579
        SemiAutoSuppressedPistolLegendary<public>: int = 580
        SentinelPumpShotgunCommon<public>: int = 581
        SentinelPumpShotgunUncommon<public>: int = 582
        SentinelPumpShotgunRare<public>: int = 583
        SentinelPumpShotgunEpic<public>: int = 584
        SentinelPumpShotgunLegendary<public>: int = 585
        ShadowMidasDrumGunMythic<public>: int = 586
        ShadowTrackerExotic<public>: int = 587
        SharpToothShotgunUncommon<public>: int = 588
        SharpToothShotgunRare<public>: int = 589
        SharpToothShotgunEpic<public>: int = 590
        SharpToothShotgunLegendary<public>: int = 591
        ShockwaveHammerEpic<public>: int = 592
        ShockwaveLauncherLegendary<public>: int = 593
        ShogunXsFireOniMaskMythic<public>: int = 594
        SidearmPistolCommon<public>: int = 595
        SidearmPistolUncommon<public>: int = 596
        SidearmPistolRare<public>: int = 597
        SidearmPistolEpic<public>: int = 598
        SidearmPistolLegendary<public>: int = 599
        SidewaysMinigunCommon<public>: int = 600
        SidewaysMinigunUncommon<public>: int = 601
        SidewaysMinigunRare<public>: int = 602
        SidewaysMinigunEpic<public>: int = 603
        SidewaysMinigunLegendary<public>: int = 604
        SidewaysMinigunMythic<public>: int = 605
        SidewaysRifleCommon<public>: int = 606
        SidewaysRifleUncommon<public>: int = 607
        SidewaysRifleRare<public>: int = 608
        SidewaysRifleEpic<public>: int = 609
        SidewaysRifleLegendary<public>: int = 610
        SidewaysRifleMythic<public>: int = 611
        SidewaysScytheCommon<public>: int = 612
        SidewaysScytheUncommon<public>: int = 613
        SidewaysScytheRare<public>: int = 614
        SidewaysScytheEpic<public>: int = 615
        SidewaysScytheLegendary<public>: int = 616
        SidewaysScytheMythic<public>: int = 617
        SixShooterUncommon<public>: int = 618
        SixShooterRare<public>: int = 619
        SixShooterEpic<public>: int = 620
        SkyesAssaultRifleMythic<public>: int = 621
        SlonesBurstAssaultRifleMythic<public>: int = 622
        SlonesPulseRifleMythic<public>: int = 623
        SnowballLauncherUncommon<public>: int = 624
        SnowballLauncherRare<public>: int = 625
        SnowballLauncherEpic<public>: int = 626
        SnowballLauncherLegendary<public>: int = 627
        SpireAssassinsPrimalShotgunMythic<public>: int = 628
        SpireAssassinsRecyclerMythic<public>: int = 629
        SpireGuardiansPrimalAssaultRifleMythic<public>: int = 630
        StickyGrenadeLauncherEpic<public>: int = 631
        StickyGrenadeLauncherLegendary<public>: int = 632
        StingerSMGCommon<public>: int = 633
        StingerSMGUncommon<public>: int = 634
        StingerSMGRare<public>: int = 635
        StingerSMGEpic<public>: int = 636
        StingerSMGLegendary<public>: int = 637
        StormScoutExotic<public>: int = 638
        StormScoutSniperRifleEpic<public>: int = 639
        StormScoutSniperRifleLegendary<public>: int = 640
        StrikerBurstRifleCommon<public>: int = 641
        StrikerBurstRifleUncommon<public>: int = 642
        StrikerBurstRifleRare<public>: int = 643
        StrikerBurstRifleEpic<public>: int = 644
        StrikerBurstRifleLegendary<public>: int = 645
        StrikerBurstRifleMythic<public>: int = 646
        StrikerPumpShotgunCommon<public>: int = 647
        StrikerPumpShotgunUncommon<public>: int = 648
        StrikerPumpShotgunRare<public>: int = 649
        StrikerPumpShotgunEpic<public>: int = 650
        StrikerPumpShotgunLegendary<public>: int = 651
        StrikerPumpShotgunMythic<public>: int = 652
        SubmachineGunCommon<public>: int = 653
        SubmachineGunUncommon<public>: int = 654
        SubmachineGunRare<public>: int = 655
        SubmachineGunBCommon<public>: int = 656
        SubmachineGunBUncommon<public>: int = 657
        SubmachineGunBRare<public>: int = 658
        SubmachineGunBEpic<public>: int = 659
        SubmachineGunBLegendary<public>: int = 660
        SubmachineGunCEpic<public>: int = 661
        SubmachineGunCLegendary<public>: int = 662
        SuppressedAssaultRifleRare<public>: int = 663
        SuppressedAssaultRifleEpic<public>: int = 664
        SuppressedAssaultRifleLegendary<public>: int = 665
        SuppressedPistolCommon<public>: int = 666
        SuppressedPistolUncommon<public>: int = 667
        SuppressedPistolRare<public>: int = 668
        SuppressedPistolEpic<public>: int = 669
        SuppressedPistolLegendary<public>: int = 670
        SuppressedSniperRifleRare<public>: int = 671
        SuppressedSniperRifleEpic<public>: int = 672
        SuppressedSniperRifleLegendary<public>: int = 673
        SuppressedSubmachineGunCommon<public>: int = 674
        SuppressedSubmachineGunUncommon<public>: int = 675
        SuppressedSubmachineGunRare<public>: int = 676
        SuppressedSubmachineGunEpic<public>: int = 677
        SuppressedSubmachineGunLegendary<public>: int = 678
        SurgefireSMGCommon<public>: int = 679
        SurgefireSMGUncommon<public>: int = 680
        SurgefireSMGRare<public>: int = 681
        SurgefireSMGEpic<public>: int = 682
        SurgefireSMGLegendary<public>: int = 683
        TacticalAssaultRifleCommon<public>: int = 684
        TacticalAssaultRifleUncommon<public>: int = 685
        TacticalAssaultRifleRare<public>: int = 686
        TacticalAssaultRifleEpic<public>: int = 687
        TacticalAssaultRifleLegendary<public>: int = 688
        TacticalDMRCommon<public>: int = 689
        TacticalDMRUncommon<public>: int = 690
        TacticalDMRRare<public>: int = 691
        TacticalDMREpic<public>: int = 692
        TacticalDMRLegendary<public>: int = 693
        TacticalPistolCommon<public>: int = 694
        TacticalPistolUncommon<public>: int = 695
        TacticalPistolRare<public>: int = 696
        TacticalPistolEpic<public>: int = 697
        TacticalPistolLegendary<public>: int = 698
        TacticalPistolMythic<public>: int = 699
        TacticalShotgunCommon<public>: int = 700
        TacticalShotgunUncommon<public>: int = 701
        TacticalShotgunRare<public>: int = 702
        TacticalShotgunEpic<public>: int = 703
        TacticalShotgunLegendary<public>: int = 704
        TacticalSubmachineGunUncommon<public>: int = 705
        TacticalSubmachineGunRare<public>: int = 706
        TacticalSubmachineGunEpic<public>: int = 707
        TacticalSubmachineGunLegendary<public>: int = 708
        TheAgelessChampionsExCaliberRifleMythic<public>: int = 709
        TheAgelessChampionsShockwaveHammerMythic<public>: int = 710
        TheBigChillExotic<public>: int = 711
        TheDubExotic<public>: int = 712
        TheMachinistsModularCombatAssaultRifleMythic<public>: int = 713
        ThermalDMRCommon<public>: int = 714
        ThermalDMRUncommon<public>: int = 715
        ThermalDMRRare<public>: int = 716
        ThermalDMREpic<public>: int = 717
        ThermalDMRLegendary<public>: int = 718
        ThermalDMRMythic<public>: int = 719
        ThermalScopedAssaultRifleEpic<public>: int = 720
        ThermalScopedAssaultRifleLegendary<public>: int = 721
        ThornesScopedBurstSMGMythic<public>: int = 722
        ThornesVampiricBladeMythic<public>: int = 723
        ThunderShotgunCommon<public>: int = 724
        ThunderShotgunUncommon<public>: int = 725
        ThunderShotgunRare<public>: int = 726
        ThunderShotgunEpic<public>: int = 727
        ThunderShotgunLegendary<public>: int = 728
        TNTinasKaBoombow<public>: int = 729
        TowHookCannonRare<public>: int = 730
        TwinMagAssaultRifleCommon<public>: int = 731
        TwinMagAssaultRifleUncommon<public>: int = 732
        TwinMagAssaultRifleRare<public>: int = 733
        TwinMagAssaultRifleEpic<public>: int = 734
        TwinMagAssaultRifleLegendary<public>: int = 735
        TwinMagSMGCommon<public>: int = 736
        TwinMagSMGUncommon<public>: int = 737
        TwinMagSMGRare<public>: int = 738
        TwinMagSMGEpic<public>: int = 739
        TwinMagSMGLegendary<public>: int = 740
        TwinfireAutoShotgunCommon<public>: int = 741
        TwinfireAutoShotgunUncommon<public>: int = 742
        TwinfireAutoShotgunRare<public>: int = 743
        TwinfireAutoShotgunEpic<public>: int = 744
        TwinfireAutoShotgunLegendary<public>: int = 745
        TwoShotShotgunCommon<public>: int = 746
        TwoShotShotgunUncommon<public>: int = 747
        TwoShotShotgunRare<public>: int = 748
        TwoShotShotgunEpic<public>: int = 749
        TwoShotShotgunLegendary<public>: int = 750
        TwoShotShotgunMythic<public>: int = 751
        TyphoonBladeEpic<public>: int = 752
        TyphoonBladeMythic<public>: int = 753
        UnstableBow<public>: int = 754
        ValeriasModularHyperSMGMythic<public>: int = 755
        VeiledPrecisionSMGCommon<public>: int = 756
        VeiledPrecisionSMGUncommon<public>: int = 757
        VeiledPrecisionSMGRare<public>: int = 758
        VeiledPrecisionSMGEpic<public>: int = 759
        VeiledPrecisionSMGLegendary<public>: int = 760
        WoodStakeShotgunRare<public>: int = 761
        WoodStakeShotgunEpic<public>: int = 762
        WoodStakeShotgunLegendary<public>: int = 763
        ZygAndChoppysRayGunMythic<public>: int = 764
        MakeshiftRifleCommon<public>: int = 765
        MakeshiftRifleUncommon<public>: int = 766
        MakeshiftRifleRare<public>: int = 767
        MakeshiftShotgunCommon<public>: int = 768
        MakeshiftShotgunUncommon<public>: int = 769
        MakeshiftShotgunRare<public>: int = 770
        HuntingRifleBUncommon<public>: int = 771
        HuntingRifleBRare<public>: int = 772
        HuntingRifleBMythic<public>: int = 773
